### ISSUE TITLE
F# 5 AOT fails with: Opcode 'r4_conv_to_i' missing from machine description file

### ISSUE THREAD

**Issue by praeclarum** [xamarin/xamarin-macios#10305]
Cannot compile apps that use FSharp.Core 5.0. AOT fails with:

```
Opcode 'r4_conv_to_i' missing from machine description file
```

FSharp.Core 4.7.2 works.

```
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/response-file.rsp 
    Xamarin.iOS 14.6.0.15 (d16-8: 87a1b18d8 using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk
    AOT Compilation exited with code 134, command:
    MONO_PATH=/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=float32 --aot=mtriple=arm64-ios,data-outfile=/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/arm64/FSharp.Core.aotdata.arm64,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/arm64/FSharp.Core.dll.s /Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/3-Build/FSharp.Core.dll
    Mono Ahead of Time compiler - compiling assembly /Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/3-Build/FSharp.Core.dll
    AOTID B2A3A5E2-1BD7-5FF6-F3B7-E85417477DC8
    Opcode 'r4_conv_to_i' missing from machine description file.
    MTOUCH : error MT3001: Could not AOT the assembly '/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/3-Build/FSharp.Core.dll'
    		
Done building target "_CompileToNative" in project "Sonar.fsproj" -- FAILED.

Done building project "Sonar.fsproj" -- FAILED.

Build FAILED.

/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/actool/cloned-assets/Assets.xcassets : actool warning : The app icon set "AppIcon" has an unassigned child.
MTOUCH : error MT3001: Could not AOT the assembly '/Users/fak/Dropbox/Projects/Sonar/obj/iPhone/Debug/device-builds/iphone12.3-14.1/mtouch-cache/3-Build/FSharp.Core.dll'
```

### Steps to Reproduce

1. New F# iOS Project
2. Add FSharp.Core 5.0 nuget
3. Build for Device Debug

### Expected Behavior

It builds/runs

### Actual Behavior

Build fails with:

```
    Opcode 'r4_conv_to_i' missing from machine description file.
```

### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: 04ce23b3-bca4-4379-9726-d678d7786aeb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.403
	3.1.402
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.100
	2.2.203
	2.2.103
	2.1.302
	2.0.3
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.9
	3.1.8
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	2.2.4
	2.2.1
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.13
	2.1.2
	2.0.3

=== .NET Core 3.1 SDK ===

SDK: 3.1.403

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Enterprise)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/fak/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/fak/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Enterprise)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Enterprise)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Meadow 0.7.5
Build Light 0.5
AddinMaker 1.5.0
MSBuild Editor 2.2.0

```

**Comment by dalexsoto** [comment]
Hello @praeclarum this has been fixed in our current preview channel and our next release, you will need a build from the xcode12.3 branch.

* [xamarin.ios-14.8.0.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12.3/c51fabee8aa096e83f7a781aecba68113613b71d/26/package/notarized/xamarin.ios-14.8.0.3.pkg)
* [xamarin.mac-7.2.0.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12.3/c51fabee8aa096e83f7a781aecba68113613b71d/26/package/notarized/xamarin.mac-7.2.0.3.pkg)

**Comment by praeclarum** [comment]
Ah I knew I should have checked the previews. I’ll try those links out thanks.

**Comment by spouliot** [comment]
Closing.

If there's a problem with the linked packages (or newer ones) please reply and we can re-open the issue. Thanks!

**Comment by Liminiens** [comment]
@dalexsoto @spouliot 

I tried preview builds but it seems that issue still exists in preview for `arm64-darwin-mono-sgen`

```
  AOT Compilation exited with code 134, command:
  MONO_PATH=.../obj/iPhone/DebugProd/device-builds/iphone11.6-14.3/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=float32 --aot=mtriple=arm64-ios,data-outfile=.../obj/iPhone/DebugProd/device-builds/iphone11.6-14.3/mtouch-cache/arm64/FSharp.Core.aotdata.arm64,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=.../obj/iPhone/DebugProd/device-builds/iphone11.6-14.3/mtouch-cache/arm64/FSharp.Core.dll.s .../obj/iPhone/DebugProd/device-builds/iphone11.6-14.3/mtouch-cache/3-Build/FSharp.Core.dll
  Mono Ahead of Time compiler - compiling assembly ../obj/iPhone/DebugProd/device-builds/iphone11.6-14.3/mtouch-cache/3-Build/FSharp.Core.dll
  AOTID 35176095-735E-CA75-9B1D-3E9D4751F826
  Opcode 'r4_conv_to_i' missing from machine description file.
```

**Comment by spouliot** [comment]
> I tried preview builds but it seems that issue still exists in preview

Your log snippet shows

> /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/bin/arm64-darwin-mono-sgen

and our current preview is 14.9.0.27, while the current stable is 14.8.0.3.

**Comment by spouliot** [comment]
hmm... 14.8.0.3 was the preview back then

It seems the fix that @dalexsoto mentioned was for `float_conv_to_i` which is a different opcode than the `r4_conv_to_i` mentioned here.

**Comment by Liminiens** [comment]
Okay, sorry :) Should I mention it here? https://github.com/mono/mono/issues/20533

**Comment by Liminiens** [comment]
i created related issue in mono: https://github.com/mono/mono/issues/20775

**Comment by spouliot** [comment]
@Liminiens great, that's what I wanted to do (but got distracted by admin tasks). It's even better as you attached a test case, which I did not have. Thanks!

**Comment by Liminiens** [comment]
@spouliot i could get a minimal example for android only now, but I will try for iOS too

**Comment by Liminiens** [comment]
Looks like `<MtouchFloat32>true</MtouchFloat32>` causes it, otherwise it doesn't fail to aot

**Comment by vshapenko** [comment]
@spouliot , are there any updates on this issue?

**Comment by akoeplinger** [comment]
https://github.com/mono/mono/issues/20775 was fixed by https://github.com/mono/mono/pull/20986, xamarin-macios needs to pick up a new build from mono's 2020-02 branch to consume it.

**Comment by rolfbjarne** [comment]
This commit bumped mono: https://github.com/xamarin/xamarin-macios/commit/a01bee4717b41ec33e798107c1b992cb90c1e574, so this is fixed (in `main`).
