### ISSUE TITLE
Attempting to JIT compile method while running in aot-only mode

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/xamarin-macios#12416]
Using [ImageSharp](https://github.com/SixLabors/ImageSharp) in a Xamarin project, it was recently [reported](https://github.com/SixLabors/ImageSharp/issues/1708) of a crash using on iOS device in release mode. I am able to replicate this with the attached project. The problem goes away if you enable mono interpreter (can also repro in debug mode if you disable mono interpreter which is the default for release, not default for debug).

Looking around it appears we should not enable the mono interpreter for release code, but there was [initially no issues](https://stackoverflow.com/a/61107515) with apps being approved with this enabled.

From what I understand the exception is throw while trying to build (build meaning not AOT?) the [ProcessRgbaScaneline](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/PngScanlineProcessor.cs#L478-L508) method, this is called in [ProcessDefilterdScanline](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L724).

Without doing a deep dive on the library myself and taking it on the [word of the project creator](https://github.com/SixLabors/ImageSharp/issues/1708#issuecomment-897207407) there is no dynamic/reflected code being executed in this library so the issue is with the Xamarin side of things.

So I guess the questions I have are:
1. Is it safe to use enable mono interpreter in a production app, if so what art the possible drawbacks?
2. Is this revealing an issue with the compiler, or is there something that was overlooked in ImageSharp code which is a no-no for Xamarin.iOS apps?
3. Is it possible and is there anything on the roadmap to improve handling of generics or is this as good as it gets?

(I was unable to try with MAUI and .NET 6 to see if this is still a problem because those have once again decided to not work on my computer again)

### Steps to Reproduce

1. Create new Xamarin.Forms project.
2. Add the [SixLabors.ImageSharp](https://github.com/SixLabors/ImageSharp) nuget package. (I added it to all projects but it didn't seem to make a difference for this issue)
3. Add a png image to the Xamarin.Forms project
4. Load that image into a byte array and try load the image like below.

```
byte[] imageData = null;
var assembly = IntrospectionExtensions.GetTypeInfo(typeof(MainPage)).Assembly;
using (var stream = assembly.GetManifestResourceStream("ImageSharpTest.Resources.icon.png"))
{
    using (var memoryStream = new MemoryStream())
    {
        stream.CopyTo(memoryStream);
        imageData = memoryStream.ToArray();
    }
}

var imageDecoder = new SixLabors.ImageSharp.Formats.Png.PngDecoder();
var image = SixLabors.ImageSharp.Image.Load(imageData, imageDecoder);
DisplayAlert("Loaded image size", $"{image.Width}x{image.Height}", "Okay");
```

### Expected Behavior

App displays an alert showing the width and height of the image.

### Actual Behavior

(iOS debug+release build on device only, with mono interpreter disabled)
App crashes with the following error
```
System.ExecutionEngineException: Attempting to JIT compile method 'void SixLabors.ImageSharp.Formats.Png.PngScanlineProcessor:ProcessRgbaScanline<SixLabors.ImageSharp.PixelFormats.Rgba32> (SixLabors.ImageSharp.Configuration,SixLabors.ImageSharp.Formats.Png.PngHeader&,System.ReadOnlySpan`1<byte>,System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32>,int,int)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ProcessDefilteredScanline[TPixel] (System.ReadOnlySpan`1[T] defilteredScanline, SixLabors.ImageSharp.ImageFrame`1[TPixel] pixels, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata) [0x0013b] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at (wrapper other) System.Object.gsharedvt_in()
  at (wrapper other) System.Object.gsharedvt_out()
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.DecodePixelData[TPixel] (System.IO.Compression.DeflateStream compressedStream, SixLabors.ImageSharp.ImageFrame`1[TPixel] image, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata) [0x000df] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at (wrapper other) System.Object.gsharedvt_in()
  at (wrapper other) System.Object.gsharedvt_out()
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel] (SixLabors.ImageSharp.Formats.Png.PngChunk chunk, SixLabors.ImageSharp.ImageFrame`1[TPixel] image, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata) [0x00047] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at (wrapper other) System.Object.gsharedvt_in()
  at (wrapper other) System.Object.gsharedvt_out()
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel] (SixLabors.ImageSharp.IO.BufferedReadStream stream, System.Threading.CancellationToken cancellationToken) [0x00163] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel] (SixLabors.ImageSharp.Formats.IImageDecoderInternals decoder, SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, System.Func`3[T1,T2,TResult] largeImageExceptionFactory) [0x00008] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel] (SixLabors.ImageSharp.Formats.IImageDecoderInternals decoder, SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00000] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00007] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00000] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Image+<>c__DisplayClass120_0.<Load>b__0 (System.IO.Stream s) [0x00000] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Image.WithSeekableStream[T] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, System.Func`2[T,TResult] action) [0x00041] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Image.Load (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, SixLabors.ImageSharp.Formats.IImageDecoder decoder) [0x00024] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Image.Load (SixLabors.ImageSharp.Configuration configuration, System.Byte[] data, SixLabors.ImageSharp.Formats.IImageDecoder decoder) [0x0000d] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at SixLabors.ImageSharp.Image.Load (System.Byte[] data, SixLabors.ImageSharp.Formats.IImageDecoder decoder) [0x00005] in <fd7f20ccdc8d46db928374008bbc5166>:0 
  at ImageSharpTest.MainPage.OnAppearing () [0x0006d] in /Users/bradmoore/Projects/ImageSharpTest/ImageSharpTest/MainPage.xaml.cs:36 
  at Xamarin.Forms.Page.SendAppearing () [0x00045] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:452 
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidAppear (System.Boolean animated) [0x0004d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:215 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at ImageSharpTest.iOS.Application.Main (System.String[] args) [0x00001] in /Users/bradmoore/Projects/ImageSharpTest/ImageSharpTest.iOS/Main.cs:17 
```

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.7 (build 17)
Installation UUID: 20fb50b3-7d66-4ddf-a724-9a931dba91c9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/Sdks
SDK Versions:
	6.0.100-preview.7.21379.14
	6.0.100-preview.6.21355.2
	6.0.100-preview.5.21302.13
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.7.21377.19
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/bradmoore/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/bradmoore/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:48:52 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:49:10 UTC

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810070017
Git revision: 503b9b053dff2e7f136e96b362a629c199f78a42
Build date: 2021-08-05 12:48:29-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.8

```

### Build Logs

Unsure if relevant, but can attach if required.

### Example Project (If Possible)

[ImageSharpTest.zip](https://github.com/xamarin/xamarin-macios/files/6972130/ImageSharpTest.zip)

**Comment by neminush** [comment]
This problem is almost a year old. And six months ago, the situation only worsened.

Here is a similar problem:
[iOS app crashes on a device with 'System.ExecutionEngineException: Attempting to JIT compile method...'](https://github.com/xamarin/xamarin-macios/issues/11691)

**Comment by spouliot** [comment]
> Is it safe to use enable mono interpreter in a production app

Yes

> if so what art the possible drawbacks?

Performance will suffer. AOT (even more if LLVM is enabled) will be much more faster than interpreting the IL.

> Is this revealing an issue with the compiler, 

Likely, but that will require more analysis from the dotnet/runtime (mono) team to confirm this.

> or is there something that was overlooked in ImageSharp code which is a no-no for Xamarin.iOS apps?

There are a few limitations when doing full AOT: https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations

> Is it possible and is there anything on the roadmap to improve handling of generics or is this as good as it gets?

It's should not be considered as final since it's consistently evolving as new features are added to .net

Based on the stack trace your issue suggest this could be related to generic sharing wrt `Span` (but I could be wrong).

Most errors will eventually reach a point showing `Attempting to JIT compile method while running in aot-only mode`, however the actual cause can differ quite a bit in each case. That's why providing a test case, like you did, is very important. Thanks!

**Comment by beeradmoore** [comment]
Thanks for the feedback @spouliot. Good to know about mono interpreter us safe to use.

If the problem is with Span<TPixel> I could see why @JimBobSquarePants may not want to refactor/remove those instances because of all the Spanny goodness.

**Comment by JimBobSquarePants** [comment]
Yeah we can’t not use `Span<T>`. Performance is important

**Comment by skir** [comment]
I've got a similar error in my project. I am using a library, which uses SignalR client. In the past everything was working fine, SignalR connection was definitely working. I didn't test this for the long time. Today I noticed that I don't get updates in my app, I started debugging and I noticed that this library is receiving `Attempting to JIT compile method while running in aot-only mode` error when it tries to set up SignalR connection. Then I enabled mono interpreter and I received `MissingMethodException` for a method that is using `ReadOnlySpan<T>`. Are there any news on this issue?

**Comment by skir** [comment]
I have just pulled a year old build of my app and installed it on device. The SignalR updates are working as expected. Then I pulled the code for this build and rebuilt it using old libraries but current Xamarin.iOS. As the result I got similar error `System.ExecutionEngineException: Attempting to JIT compile method 'int System.Text.Json.JsonWriterHelper:NeedsEscaping (System.ReadOnlySpan`1<byte>,System.Text.Encodings.Web.JavaScriptEncoder)' while running in aot-only mode` when mono interpreter is disabled, and ` System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)` when mono interpreter is enabled.
So, I suspect that something broke in Xamarin.iOS in the past year. Are the any fixes? Or should I try to use older Xamarin.iOS?

**Comment by rolfbjarne** [comment]
This might have been fixed with https://github.com/xamarin/xamarin-macios/pull/14109, which will be included with our upcoming release to support Xcode 13.3.

**Comment by beeradmoore** [comment]
Unsure if the issues skir were having is 100% related to the original issue, but I double checked the sample for this issue and it is still broken with the current fully updates VS setup below.


```
Visual Studio Community 2019 for Mac
Version 8.10.21 (build 4)
Installation UUID: 9d4385c8-d6e6-44ec-bd19-523cd9b7e616
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

Mono Framework MDK
Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
Version: 5.9.0.7134

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.201/Sdks
SDK Versions:
	6.0.201
	6.0.200
	6.0.102
	6.0.101
	6.0.100-rc.1.21463.6
	6.0.100-preview.7.21379.14
	6.0.100-preview.6.21355.2
	6.0.100-preview.5.21302.13
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.200
	5.0.103
	5.0.102
	5.0.101
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.3
	6.0.2
	6.0.1
	6.0.0-rc.1.21451.13
	6.0.0-preview.7.21377.19
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Updater
Version: 11

Apple Developer Tools
Xcode 13.3 (20102)
Build 13E113

Xamarin.Mac
Version: 8.8.0.0 (Visual Studio Community)
Hash: f10d9e023
Branch: xcode13.3
Build date: 2022-03-15 11:47:34-0400

Xamarin.iOS
Version: 15.8.0.0 (Visual Studio Community)
Hash: f10d9e023
Branch: xcode13.3
Build date: 2022-03-15 11:47:35-0400

Xamarin Designer
Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

Xamarin.Android
Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/bradmoore/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

Build Information
Release ID: 810210004
Git revision: eb0b2f7259d35b7d767c79d91d356881227e0985
Build date: 2022-03-17 17:18:28-04
Build branch: release-8.10

Operating System
Mac OS X 12.3.0
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Mon Feb 21 20:34:37 PST 2022
    root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
MFractor 4.4.10
```

**Comment by juwens** [comment]
> This might have been fixed with #14109, which will be included with our upcoming release to support Xcode 13.3.

For my issue (microsoft/onnxruntime#11394) this seems to fix it. 👍

**Comment by rolfbjarne** [comment]
Thanks for confirm this!

I'm closing the issue, if anybody runs into this error (`Attempting to JIT compile method ...`), please file a new issue and include a test project we can use to reproduce the error.

**Comment by beeradmoore** [comment]
@rolfbjarne , issue still occurs with the same exception. Test project in the initial post has the same issue (in release mode OR debug mode with mono interpreter disabled). I have updated test project with latest nuget packages, most notably updating ImageSharp from v1 to v2 (although no code changes were required). I also disabled mono interpreter for debug device builds for this one so it should be easier to just download and run it without having of faff about with config files yourself.

[ImageSharpTest.zip](https://github.com/xamarin/xamarin-macios/files/8617297/ImageSharpTest.zip)

Current dev environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.22 (build 11)
Installation UUID: b137c7fe-c3fc-40d8-8172-d978456dbf95
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000174

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.174 (2020-02/adf1bc4335d) (64-bit)
	Package version: 612000174

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.300/Sdks
SDK Versions:
	6.0.300
	6.0.202
	6.0.201
	6.0.200
	6.0.102
	6.0.101
	6.0.100-rc.1.21463.6
	6.0.100-preview.7.21379.14
	6.0.100-preview.6.21355.2
	6.0.100-preview.5.21302.13
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.200
	5.0.103
	5.0.102
	5.0.101
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	6.0.0-rc.1.21451.13
	6.0.0-preview.7.21377.19
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.418

=== .NET 5.0 SDK ===

SDK: 5.0.407

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.3.1 (20103)
Build 13E500a

=== Xamarin.Mac ===

Version: 8.8.0.3 (Visual Studio Community)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

=== Xamarin.iOS ===

Version: 15.8.0.3 (Visual Studio Community)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Xamarin.Android ===

Version: 12.2.4.3 (Visual Studio Community)
Commit: xamarin-android/d17-1/fc1125e
Android SDK: /Users/bradmoore/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: adf1bc4
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810220011
Git revision: 16b49eb779f7def4523bbc8f4407628cf8dbb4b5
Build date: 2022-04-07 05:04:03-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.3.1
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Fri Mar 18 00:45:05 PDT 2022
    root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.10

```

**Comment by rolfbjarne** [comment]
@beeradmoore correct, I can still reproduce too with the updated sample.

I've also updated https://github.com/mono/mono/issues/21187 with more information.

**Comment by goatrodeosoftware** [comment]
I've got the same issue too, if it helps. It'd be a bear to attach my project, but let me know if there's something else I can do to help.

**Comment by beeradmoore** [comment]
@rolfbjarne , this is still an issue after todays round of updates (environment listed below). Would I be right in thinking that this build didn't make it to the VS4Mac update that all went out today? It looks like after that update I am still on Mono 6.12.0.174 (2020-02/adf1bc4335d). Is there any thing I can do to try the updated version of this or does it also involve building Xamarin.iOS from source? 

I see there are a few new versions in the [mono archives](https://download.mono-project.com/archive/6.12.0/macos-10-universal/?C=M;O=D) but unsure what relates to what changes being done.

Current environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.23 (build 7)
Installation UUID: 096d5d7c-739a-4823-99b2-51a1409606c1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000174

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.174 (2020-02/adf1bc4335d) (64-bit)
	Package version: 612000174

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.102/Sdks
SDK Versions:
	6.0.300
	6.0.202
	6.0.201
	6.0.200
	6.0.102
	6.0.101
	6.0.100-rc.1.21463.6
	6.0.100-preview.7.21379.14
	6.0.100-preview.6.21355.2
	6.0.100-preview.5.21302.13
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.200
	5.0.103
	5.0.102
	5.0.101
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	6.0.0-rc.1.21451.13
	6.0.0-preview.7.21377.19
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.419

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.3.1 (20103)
Build 13E500a

=== Xamarin.Mac ===

Version: 8.10.0.1 (Visual Studio Community)
Hash: 568bdb24e
Branch: d17-2
Build date: 2022-04-08 18:52:56-0400

=== Xamarin.iOS ===

Version: 15.10.0.1 (Visual Studio Community)
Hash: 568bdb24e
Branch: d17-2
Build date: 2022-04-08 18:52:57-0400

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Xamarin.Android ===

Version: 12.3.0.3 (Visual Studio Community)
Commit: xamarin-android/d17-2/bbba5a2
Android SDK: /Users/bradmoore/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: adf1bc4
Java.Interop: xamarin/java.interop/d17-2@9760f0a9
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.38.2@7b1e016
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810230007
Git revision: 7f00a2236acfde86feffbab606eefae32a9adbb3
Build date: 2022-05-05 09:46:09-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.3.1
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Fri Mar 18 00:45:05 PDT 2022
    root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.10

```

**Comment by rolfbjarne** [comment]
@beeradmoore 

> Would I be right in thinking that this build didn't make it to the VS4Mac update that all went out today?

Correct, it got fixed too late for today's release.

I'll see if I can get a package available for you to use.

**Comment by beeradmoore** [comment]
There is nothing urgent or critical requiring getting this. Was more interested to play.

If it takes away from time spent better doing other things I am more than happy to wait until next release.

**Comment by rolfbjarne** [comment]
> There is nothing urgent or critical requiring getting this. Was more interested to play.

Too late :)

This is a package with the fix: https://bosstoragemirror.blob.core.windows.net/wrench/d17-2/874bc6428d5a03f2e12a095a3e952635f7d3354e/6139528/package/notarized/xamarin.ios-15.10.0.4.pkg

**Comment by beeradmoore** [comment]
Demo now works <3

**Comment by cjlotz** [comment]
@rolfbjarne  Any idea/way to track when this will become available as part of official Xamarin release?

**Comment by rolfbjarne** [comment]
@cjlotz I'm not quite sure when this will be released, but it will be included in the next update whenever that is (should be in the order of weeks).

**Comment by cjlotz** [comment]
@rolfbjarne  I'm tempted to use the package you provided, but not sure how to rollback to my current version if that does not fix the problem.  Is there a way to download a specific version of xamarin.ios pkg?   Here's my current setup

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.23 (build 7)
Installation UUID: f3fbc680-347c-43f7-8369-4a70c1a1f693
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000174

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.174 (2020-02/adf1bc4335d) (64-bit)
	Package version: 612000174

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.100/Sdks
SDK Versions:
	6.0.201
	6.0.100
	5.0.408
	5.0.407
	3.1.419
	3.1.418
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.3
	6.0.0
	5.0.17
	5.0.16
	3.1.25
	3.1.24

=== .NET Core 3.1 SDK ===

SDK: 3.1.419

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Apple Developer Tools ===

Xcode 13.3.1 (20103)
Build 13E500a

=== Xamarin.Android ===

Version: 12.2.4.3 (Visual Studio Enterprise)
Commit: xamarin-android/d17-1/fc1125e
Android SDK: /Users/carell/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: adf1bc4
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Xamarin.Mac ===

Version: 8.8.0.3 (Visual Studio Enterprise)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

=== Xamarin.iOS ===

Version: 15.8.0.3 (Visual Studio Enterprise)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

=== Build Information ===

Release ID: 810230007
Git revision: 7f00a2236acfde86feffbab606eefae32a9adbb3
Build date: 2022-05-05 09:46:09-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.3.1
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Fri Mar 18 00:45:05 PDT 2022
    root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
```

**Comment by rolfbjarne** [comment]
@cjlotz if you're using VSMac, then you can just "upgrade" to the latest stable version in VSMac to roll back. If that doesn't work, we can provide the download link to the stable pkg as well.

**Comment by StephaneDelcroix** [comment]
@rolfbjarne Rolf, some Maui user reported this today, and I think it's related https://github.com/dotnet/maui/issues/7396. Is it fixed, or is it a new case of the same problem ? Thx

**Comment by rolfbjarne** [comment]
@StephaneDelcroix it's hard to say because the error message is quite generic. However, the bug belongs in dotnet/runtime, so you can just move it there.
