### ISSUE TITLE
Info.plist isn't copied when using NativeReference to a framework

### ISSUE THREAD

**Issue by dotMorten** [xamarin/xamarin-macios#13665]
### Steps to Reproduce
(note: repro project attached at the bottom, so you can skip to step 3)
1.  From a PC with a mac remotely connected, create a new project 'iOS Application (Preview)`
2. Add the package `Esri.ArcGISRuntime.runtimes.iOS` v100.13.0 (note this is an unlisted package, and contains a framework file with two `<NativeReference/>` links to the frameworks it includes.
  `<PackageReference Include="Esri.ArcGISRuntime.runtimes.iOS" Version="100.13.0" />`
3. Build and remote deploy to a device.
4. Observe the following error when the application is getting copied to the device:
> '/Users/mort5161/Library/Caches/Xamarin/mtbs/builds/iOSApp4/03a96aee289517c226dd58fcadd3dab545d25ace347ce3ed556000e93072db0f/bin/Debug/net6.0-ios/ios-arm64/device-builds/iphone11.6-14.8.1/iOSApp4.app' on the device 'Morten???s work iPhone': Package Inspection Failed Error (error: 0xe8000051).		 	0	

Build log:
```
 TakingInstallLock - PercentComplete: 20%
 PreflightingApplication - PercentComplete: 30%
 PackageInspectionFailed: Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.e6zQ7M/extracted/iOSApp4.app/Frameworks/Runtimecore.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.e6zQ7M/extracted/iOSApp4.app/Frameworks/Runtimecore.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.e6zQ7M/extracted/iOSApp4.app/Frameworks/Runtimecore.framework/Info.plist: No such file or directory
2>Deploy failed
```
Browsing through the deployment of files, you'll also note these files aren't in the list.

As a workaround the two `Info.plist` files can manually be included like this and deployment will succeed:
```xml
    <ItemGroup>
        <PackageReference Include="Esri.ArcGISRuntime.runtimes.iOS" Version="100.13.0" GeneratePathProperty="true"  />
        <None Include="$(PkgEsri_ArcGISRuntime_runtimes_iOS)\framework\ios-arm64\native\Runtimecore.framework\Info.plist" Link="Frameworks/Runtimecore.framework/Info.plist">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="$(PkgEsri_ArcGISRuntime_runtimes_iOS)\framework\ios-arm64\native\ArcGIS-arm64.framework\Info.plist" Link="Frameworks/ArcGIS-arm64.framework/Info.plist">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
```

Repeat this behavior an app targeting the older xamarinios TFM instead of .NET 6. The `<NativeReference />` is included the same way, and does not fail to deploy.

### Expected Behavior
Info.plist files are copied as part of the `NativeReference`

### Actual Behavior
Deployment fails - files aren't copied as they should be

### Environment
Microsoft Visual Studio Enterprise 2022
Version 17.1.0 Preview 2.0
VisualStudio.17.Preview/17.1.0-pre.2.0+32104.313
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA974
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.1.229.41008
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.229.41008
Azure App Service Tools v3.0.0

C# Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.1203.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21561.4+56d49a0f5a876dbadeaf34af91972c7a10de858b
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.1.0.269 (main@be6679a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.99.117 (main/c52e6e6)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@7f1a5ab1
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.0@88e12a9
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@35c89dd

Xamarin.iOS and Xamarin.Mac SDK   15.3.0.215 (faa966ba2)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Example Project (If Possible)
[iOSApp4.zip](https://github.com/xamarin/xamarin-macios/files/7840825/iOSApp4.zip)

**Comment by rolfbjarne** [comment]
This might have been fixed by #13591.

**Comment by rolfbjarne** [comment]
This seems to be working fine now.

**Comment by dotMorten** [comment]
Thanks @rolfbjarne. I'm not getting this error any longer. However the attached repro now causes the below error instead, which occur even before the copying starts. Which version do I need? (I got latest VS 17.2 preview, .net6.0.2 and up to date maui workloads)
```
1>--custom-step "Xamarin.GenerateMainStep,/Users/mort5161/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/dotnet-linker/dotnet-linker.dll"
1>--custom-step "Xamarin.GenerateReferencesStep,/Users/mort5161/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/dotnet-linker/dotnet-linker.dll"
1>--custom-step "Xamarin.GatherFrameworksStep,/Users/mort5161/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/dotnet-linker/dotnet-linker.dll"
1>--custom-step "Xamarin.Linker.ComputeNativeBuildFlagsStep,/Users/mort5161/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/dotnet-linker/dotnet-linker.dll"
1>--custom-step "Xamarin.Linker.ComputeAOTArguments,/Users/mort5161/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/dotnet-linker/dotnet-linker.dll"
1>--custom-step "Xamarin.Linker.DoneStep,/Users/mort5161/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/dotnet-linker/dotnet-linker.dll"
1>--skip-unresolved true  --custom-data "LinkerOptionsFile=obj/Debug/net6.0-ios/ios-arm64/custom-linker-options.txt" --verbose -b --disable-opt unusedtypechecks
1>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning : [xma]: Unable to authenticate using the following authentication method: PrivateKeyAuthenticationMethod
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning : Safe handle has been closed
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at System.Security.Cryptography.Utils.HashData(SafeHashHandle hHash, Byte[] data, Int32 cbData, Int32 ibStart, Int32 cbSize)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at System.Security.Cryptography.SHA1CryptoServiceProvider.HashCore(Byte[] rgb, Int32 ibStart, Int32 cbSize)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at Renci.SshNet.Security.Cryptography.RsaDigitalSignature.Hash(Byte[] input)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at Renci.SshNet.Security.Cryptography.CipherDigitalSignature.Sign(Byte[] input)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at Renci.SshNet.Security.Key.Sign(Byte[] data)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at Renci.SshNet.Security.KeyHostAlgorithm.Sign(Byte[] data)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at Renci.SshNet.PrivateKeyAuthenticationMethod.Authenticate(Session session)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(1055,3): warning :    at Xamarin.Messaging.Ssh.MessagingAuthenticationMethod.TryAuthenticate(Session session, AuthenticationMethod method) in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingAuthenticationMethod.cs:line 118
1>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s obj/Debug/net6.0-ios/ios-arm64/mtouch-symbols.list obj/Debug/net6.0-ios/ios-arm64/nativelibraries/iOSApp4
1>/usr/bin/ditto C:/Users/mn/.nuget/packages/esri.arcgisruntime.runtimes.ios/100.13.0/framework/ios-arm64/native/ArcGIS-arm64.framework/ bin/Debug/net6.0-ios/ios-arm64/publish/../iOSApp4.app//Frameworks//ArcGIS-arm64.framework
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.7\targets\Xamarin.Shared.Sdk.targets(653,3): error MSB6006: "ditto" exited with code 1.
1>Done building project "iOSApp4.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by rolfbjarne** [comment]
@mauroa @emaf have you seen the error above before?

**Comment by dotMorten** [comment]
@rolfbjarne There are a few old issues mentioning similar issues with Ditto.

**Comment by rolfbjarne** [comment]
Reopening since I failed to read point 1 in the instructions: use windows (according to the reporter this is only reproducible from windows).

**Comment by rolfbjarne** [comment]
Unfortunately, the team in question are not accessible from github issues here. You'll need to report an issue [here](https://developercommunity.visualstudio.com/report?space=8&entry=problem) to get it sent to the correct group.

I'm sorry for the trouble

**Comment by dotMorten** [comment]
VS Community issue logged: https://developercommunity.visualstudio.com/t/net6-ios-infoplist-isnt-copied-when-using-nativere/1677609

**Comment by samhouts** [comment]
@rolfbjarne Tooling team took a look at this issue. According to @emaf, "this looks like a problem on how the targets are referencing the frameworks. "

**Comment by dotMorten** [comment]
Similar issue wrt Ditto: https://github.com/xamarin/xamarin-macios/issues/11817

**Comment by rolfbjarne** [comment]
I can reproduce a problem with ditto.

**Comment by rolfbjarne** [comment]
It looks like this problem is fixed in preview 14: once I fixed the `ditto` problem, I'm able to launch the test project on device from Windows.

**Comment by rolfbjarne** [comment]
Preview 14 has been released, it would be great if you could confirm that this is fixed!

https://devblogs.microsoft.com/dotnet/dotnet-maui-preview-14/

**Comment by dotMorten** [comment]
@rolfbjarne On it! Just gotta fix all the things you broke first :-)

**Comment by dotMorten** [comment]
@rolfbjarne I'm not having much luck still with the above repro. It does look like it is getting further now and complaining that min-version isn't 13 which my framework requires, but after fixing that I'm still met with a bit of an unhelpful clang++ error.
```
1>--skip-unresolved true  --custom-data "LinkerOptionsFile=obj/Debug/net6.0-ios/ios-arm64/custom-linker-options.txt" --verbose -b --disable-opt unusedtypechecks --feature ObjCRuntime.Runtime.Arch.IsSimulator false
1>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Tool xcrun execution finished (exit code = 1).
1>Undefined symbols for architecture arm64:
1>  "_mono_fconv_u8_2", referenced from:
1>      wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u8_double in System.Private.CoreLib.dll.o
1>  "_mono_fconv_u4_2", referenced from:
1>      wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u4_double in System.Private.CoreLib.dll.o
1>ld: symbol(s) not found for architecture arm64
1>clang: error: linker command failed with exit code 1 (use -v to see invocation)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\targets\Xamarin.Shared.Sdk.targets(1197,3): error : clang++ exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\targets\Xamarin.Shared.Sdk.targets(1197,3): error :
1>Done building project "iOSApp4.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by dotMorten** [comment]
I should add this still happens without my package, so probably something else I'm hitting, but it does make it so I can't confirm this issue is fixed

**Comment by rolfbjarne** [comment]
@dotMorten:

It looks like the wrong bits are installed on the mac.

Can you:

1. Close VS (Windows).
2. Delete the `~/Library/Caches/Xamarin/XMA` directory on your mac.
3. Restart VS (Windows), connect to the mac.
4. Enable diagnostic build output of you haven't already.
5. Attach the 'Xamarin' + 'Build' logs from VS (the first one is the log from connecting to the mac and re-installing .NET there, the second is from the build itself).

**Comment by rolfbjarne** [comment]
@dotMorten did you delete the `~/Library/Caches/Xamarin/XMA/SDKs` directory on the mac?

The 2022-03-17_11-17-05.40920.Ide file says:

> The dotnet SDK is already installed. Version: '6.0.300-preview.22154.4': 03/17/2022 18:17:19Z

**Comment by dotMorten** [comment]
@rolfbjarne  yes all of xma

**Comment by rolfbjarne** [comment]
@dotMorten can you try the "macOS / macOS Build Host Preview 14 installation" workaround at the end of the readme here: https://github.com/dotnet/maui/releases/tag/6.0.200-preview.14.2?

**Comment by rolfbjarne** [comment]
@dotMorten I believe this should be fixed now, in this service release: https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#1720-pre21--visual-studio-2022-version-172-preview-21

**Comment by dotMorten** [comment]
Woohoo! Finally some success! Ran built, and even was able to call into the native framework with remote deploy!

**Comment by rolfbjarne** [comment]
That's great! And thanks for confirming that it works now.
