### ISSUE TITLE
A DllNotFoundException is thrown when calling into an iOS binding library when using MAUI on iOS

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#17418]
---
**Issue moved from dotnet/maui#13039**
- Please respond to @whodges.

---

_From @whodges on Wednesday, February 1, 2023 2:31:00 AM_

### Description

I followed the instructions here (https://learn.microsoft.com/en-us/xamarin/cross-platform/cpp/) to access C++ native libraries from C# across multiple platforms.  While I was able to get this working in MAUI on Windows and Android, I can't get it to work on iOS.  Accessing the library throws a DllNotFoundException in MAUI under iOS (which is odd because DllImport is being passed "__Internal"; it's as if it's actually trying to load a library named as such).  For the C# iOS native lib wrapper, I've used the "iOS Binding Library" project template.  Note that this is not the Xamarin iOS binding library, it's the .NET one.

I created a full example of the problem I'm running into here:  https://github.com/whodges/bindingsample/tree/main.  This is the default template MAUI app, but it uses a native C++ counter from C# to keep track of how many times the button has been clicked, rather than just a '_count' member variable.   Windows and Android work fine; they're native libraries get used perfectly.  Using Visual Studio 17.5.0 Preview 5.0 on Windows, it fails on iOS as follows:

![screenshot](https://user-images.githubusercontent.com/5587254/215929166-cd985c15-f5a5-45f9-b9ad-c69e40bdc7f8.png)

### Steps to Reproduce

1. Clone the repo here:  https://github.com/whodges/bindingsample/tree/main
2. Build the solution and deploy to am ARM64 iOS device (I was using a physical iPhone 14 Pro).  Note building CounteriOS requires you be paired with a Mac running VCRemote (Tools->Options->Cross Platform->C++->iOS->Pairing).  If a Mac isn't available, you can actually just remote CounteriOS (NOT Counter.iOS) from the solution as Counter.iOS already has a pre-built copy of libCounteriOS.a to reference.
3. Debug the solution.  A DllNotFoundException will be thrown whenever a method in CounterWrapper gets called.

### Link to public reproduction project repository

https://github.com/whodges/bindingsample/tree/main

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

Nope.

**Comment by rolfbjarne** [comment]
I tried running the BasicMauiApp project on an iOS device from the Mac directly, and that worked just fine.

Could you try that and see if it works for you as well? This would allow us to narrow down where things go wrong.

**Comment by whodges** [comment]
Can I ask how you did that?  Did you build the solution using Visual Studio for Mac?  I tried that but Visual Studio for Mac can't load BindingSample.sln as it can't load the C++ .vcxproj projects.  As a workaround, I made BindingSampleMac.sln (see my latest commits) which doesn't contain the C++ projects (nor the Windows ones), but Visual Studio for Mac doesn't seem to respect conditional project references, meaning net7.0-android, net7.0-ios, and net7.0-maccatalyst all end up referencing Counter.Android, and the build fails accordingly.  I'm using Visual Studio for Mac 17.4.4 (build 12).

**Comment by rolfbjarne** [comment]
> Can I ask how you did that? Did you build the solution using Visual Studio for Mac? I tried that but Visual Studio for Mac can't load BindingSample.sln as it can't load the C++ .vcxproj projects. As a workaround, I made BindingSampleMac.sln (see my latest commits) which doesn't contain the C++ projects (nor the Windows ones), but Visual Studio for Mac doesn't seem to respect conditional project references, meaning net7.0-android, net7.0-ios, and net7.0-maccatalyst all end up referencing Counter.Android, and the build fails accordingly. I'm using Visual Studio for Mac 17.4.4 (build 12).

I built using the command line, and that worked just fine.

Can you try removing the non-ios target frameworks and projects (net7.0-android/net7.0-maccatalyst), and see if that gets you further?

**Comment by whodges** [comment]
Ok, so when I removed all of the non-iOS target frameworks, built the now-iOS-only solution using Visual Studio for Mac, and deployed it to my phone, it worked!  Which is great.  But I'd love to do all this on my Windows machine and just use Visual Studio for Windows.  One interesting note is that, on VS for Mac, Counter.iOS/bin/Debug/net7.0-ios ends up with a 'Counter.resources' folder, which subsequently contains 'libCounteriOS.a' and 'manifest'.  This 'Counter.resources' folder doesn't get created when I build the solution using VS for Windows.

Happy to try more things if it helps narrow down the issue!

**Comment by rolfbjarne** [comment]
Try adding this to your binding project (https://github.com/whodges/bindingsample/blob/main/Counter.iOS/Counter.iOS.csproj):

```xml
<PropertyGroup>
   <NoBindingEmbedding>false</NoBindingEmbedding>
</PropertyGroup>
```

This will embed the `libCounteriOS.a` file inside the Counter.dll assembly as a resource instead of putting it next to the assembly.

If that doesn't work, try to build the binding project (only) on your Mac, and then reference the `Counter.dll` assembly in your main iOS project (as opposed to referencing the binding project).

**Comment by whodges** [comment]
I've tried these things before, but not every permutation.  So here's what I did this morning:

1. Set 'NoBindingEmbedding' to 'false' and build/run on VS Windows (to my iPhone).  Unsuccessful, and the size of Counter.dll doesn't change (it's still about 6 KB).
2. Set 'NoBindingEmbedding' to 'false' and build/run on VS Mac.  Successful, and the size of Counter.dll increases from 6 KB to 14 KB.
3. Remove the project refences to Counter.iOS from BasicMauiApp.  Add a pre-build step to BasicMauiApp that copies the contents of the bin folder of Counter.iOS from my MacBook (built with VS Mac).   Add an assembly reference in BasicMauiApp to that copied Counter.iOS assembly.  Build/run on VS Windows.  Unsuccessful, despite having the 14 KB Counter.dll and the 'Counter.resources' folder and its contents.

**Comment by rolfbjarne** [comment]
Can you get a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for step 3?

**Comment by whodges** [comment]
Done.  I added the output msbuild.binlog for step 3 to the root of my git repo since I couldn't attach it here.

**Comment by rolfbjarne** [comment]
@whodges it seems that build was done without a connection to the mac:

> Property IsMacEnabled = false

Linking with a static library requires a connection to the mac.

Can you try connecting to the Mac (using the [Pair to Mac feature for Xamarin](https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/)) and see if that changes anything?

**Comment by whodges** [comment]
Repeated step 3 while ensuring that I was paired with my MacBook in Options->Xamarin->iOS Settings.  Still unsuccessful.  Updated msbuild.binlog.

**Comment by rolfbjarne** [comment]
@whodges it seems that's still not connected to the Mac during the build.

Did you get that binlog by building from the command line or from inside Visual Studio?

If you built from the command line, you need to pass some additional properties to the build process for the build to connect to the Mac: https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#build-ios-apps-from-the-windows-command-line (ServerAddress, ServerUser and ServerPassword)

**Comment by whodges** [comment]
Ok - this time I ran the following command line on a fresh clone:

```msbuild BindingSample.sln /bl:msbuild.binlog /p:ServerAddress=[macbookip] /p:ServerUser=wes.hodges /p:ServerPassword=[macbookpassword]```

This, however, generated some build errors.  I'm not sure what to do about them.  Note that running ```msbuild BindingSample.sln /bl:msbuild.binlog``` works just fine on a fresh clone.  In the error messages below, there's the path ```/Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/Counter.iOS/4d19a3db64c3ddf6654c92c7086342fa6dab6
3a974b36645d1f7906594c825b0/obj/Debug/net7.0-ios/iossimulator-x64/actool/bundle/Assets.car```.  The ```iossimulator-x64```folder doesn't exist though.  It's also odd to me that it's looking for this folder inside ```net7.0-ios```.  Note that I also updated the ```msbuild.binlog``` file in the repo.

```C:\Projects\bindingsample\BindingSample.sln" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (default target) (2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (Build target) (2:4) ->
(_CopyResourcesToBundle target) ->
  C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error : System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/Counter.iOS/4d19a3db64c3ddf6654c92c7086342fa6dab6
3a974b36645d1f7906594c825b0/obj/Debug/net7.0-ios/iossimulator-x64/actool/bundle/Assets.car". [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean ano
nymous, System.IO.FileOptions options) [0x0015e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:223  [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOpti
ons options) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:106  [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions) [C:\Projects\b
indingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00025] in /Users/builder/jenkins/workspace/build-packa
ge-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:54  [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00056] in /Users/builder/jenkins/workspace/build-package-osx-mon
o/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:74  [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at Xamarin.MacDev.Tasks.SmartCopyTaskBase.CopyFile (System.String source, System.String target, System.String targetItemSpec) [0x00030] in /Users/builder/azdo/_work/2/s/xamari
n-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs:64  [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1157,3): error :   at Xamarin.MacDev.Tasks.SmartCopyTaskBase.Execute () [0x000d2] in /Users/builder/azdo/_work/2/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs:97  [C:\
Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]```

**Comment by rolfbjarne** [comment]
It looks like you're running into a different problem, where the remote build gets confused about which project is building and mixes up directories between them. We've already fixed this, but I'm note sure we've released the fix.

In any case, a potential workaround would be to instead of having a PackageReference in the BasicMauiApp.cs to the Counter.iOS.csproj, use a direct reference to the assembly from that project instead:

```xml
<ItemGroup>
    <Reference Include="path/to/Counter.iOS/bin/Debug/net7.0-ios/Counter.dll" />
</ItemGroup>
```

**Comment by whodges** [comment]
I did what you suggested, and it didn't change anything.  Then, in addition to that, I wiped out the Library/Caches/Xamarin folder on my Macbook after reading posts on similar errors, and that seemed to help.  However, now I get:

'''"C:\Projects\bindingsample\BindingSample.sln" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj.metaproj" (default target) (2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (default target) (6) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (Build target) (6:2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (_ComputeFilesToPublishForRuntimeIdentifiers target) (6:3) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (default target) (5:8) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (Build target) (5:9) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (Clean target) (5:10) ->
(ResolvePackageAssets target) ->
  C:\Program Files\dotnet\sdk\7.0.200-preview.22628.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file 'C:\Projects\bindingsample\Counter.iOS\obj\project.assets.json' doesn't have a target for 'net7.0-ios/android-arm64'. Ensure
 that restore has run and that you have included 'net7.0-ios' in the TargetFrameworks for your project. You may also need to include 'android-arm64' in your project's RuntimeIdentifiers. [C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj::TargetFramework=net7.0-ios]


"C:\Projects\bindingsample\BindingSample.sln" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj.metaproj" (default target) (2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (default target) (6) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (Build target) (6:2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (_ComputeFilesToPublishForRuntimeIdentifiers target) (6:3) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (default target) (5:8) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (Build target) (5:11) ->
  C:\Program Files\dotnet\sdk\7.0.200-preview.22628.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file 'C:\Projects\bindingsample\Counter.iOS\obj\project.assets.json' doesn't have a target for 'net7.0-maccatalyst/android-arm64'
. Ensure that restore has run and that you have included 'net7.0-maccatalyst' in the TargetFrameworks for your project. You may also need to include 'android-arm64' in your project's RuntimeIdentifiers. [C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj::TargetFramework=net7.0-maccatal
yst]


"C:\Projects\bindingsample\BindingSample.sln" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj.metaproj" (default target) (2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (default target) (6) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (Build target) (6:4) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (GetCopyToPublishDirectoryItems target) (5:15) ->
  C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj : error MSB4057: The target "GetCopyToPublishDirectoryItems" does not exist in the project.'''

A few people seem to be facing NETSDK1047.  I can't find any clear solution but will keep trying.

**Comment by rolfbjarne** [comment]
This is weird, it seems that you're still building the Counter.iOS.csproj project even though the BasicMauiApp.csproj doesn't have a reference to it anymore:

> "C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (default target) (5:8) ->

Are you building the entire solution, or just the BasicMauiApp.csproj project? Can you try removing the Counter.iOS.csproj from the solution? Also maybe clean the bin/obj folders.

**Comment by whodges** [comment]
My bad:  yes, I was building the entire solution, and that last build was building Counter.iOS.  I modified the solution to simply have BasicMauiApp.csproj reference the prebuilt Counter.iOS.dll assembly that my Macbook built (I uploaded these changes to my repository, including the pre-built binaries (and binlog), so you might be able to reproduce this).  I still have errors.  I'll be on vacation until Feb 16 - will this issue stay open that long, or will it auto-close after 7 days?  And here's my latest build error output (again, I appreciate your time and help on this):

```"C:\Projects\bindingsample\BindingSample.sln" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (default target) (2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (Build target) (2:7) ->
(_RunILLink target) ->
  C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(332,3): error MSB6006: "dotnet" exited with code 1. [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]


"C:\Projects\bindingsample\BindingSample.sln" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (default target) (2) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj" (Build target) (2:7) ->
  C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(373,3): error MSB3371: The file "obj\Debug\net7.0-ios\iossimulator-x64\linked\Link.semaphore" cannot be created. Could not find a part of the path 'C:\Projects\bindingsample\
BasicMauiApp\obj\Debug\net7.0-ios\iossimulator-x64\linked\Link.semaphore'. [C:\Projects\bindingsample\BasicMauiApp\BasicMauiApp.csproj::TargetFramework=net7.0-ios]

**Comment by rolfbjarne** [comment]
The build is using the system .NET installation on the Mac:

> Property _DotNetRootRemoteDirectory = /usr/local/share/dotnet/

but I'm guessing that's a different version that what's installed on Windows, because it fails finding some files:

> * You intended to execute a .NET program, but /usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.ILLink.Tasks/build/../tools/net7.0/illink.dll does not exist.

You must have exactly the same version installed on both Windows and Mac.

> I'll be on vacation until Feb 16 - will this issue stay open that long, or will it auto-close after 7 days?

We'll keep it open until then, don't worry about it :)

**Comment by whodges** [comment]
Ok, I'm back, and I appreciate you keeping this open :)  I've been working on this today, and uploaded a new .binlog.  Two questions:

My Macbook now has VS 17.5 with the .NET SDK 7.0.200, so those 'missing SDK' errors are gone.  Building from the command line, I now get:

`C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1738,3): error : Could not find Microsoft.iOS in /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1007/. [C:\Projects\bindingsample\BasicMauiApp\BasicMauiAppMac.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1007\tools\msbuild\iOS\Xamarin.Shared.targets(1738,3): error :          [C:\Projects\bindingsample\BasicMauiApp\BasicMauiAppMac.csproj::TargetFramework=net7.0-ios]`

My Macbook has versions 16.2.19 and 16.2.1024 of Microsoft.iOS.Sdk in `/usr/local/share/dotnet/packs/`.  I've tried to getversion 16.2.1007 via Nuget in Visual Studio for Mac by adding it as a package to Counter.iOS, but when I do I get a `Package 'Microsoft.iOS.Sdk 16.2.1007' has a package type 'DotnetPlatform' that is not supported by project 'Counter.iOS'`.  Is there some other way I can get that Nuget package on my Macbook?  I'm not especially Macbook savvy.

Second, do I ultimately need both an ARM64 and an x64 build of libCounteriOS.a?  It seems like I do - my iPhone needs an ARM64 build, and the iOS Simulator needs an x64 one.  However, I'm struggling with how to how to handle both on the MAUI side.  That is, it's easy enough to make ARM64 and x64 builds of Counter.iOS that link/bind to the respective libCounteriOS.a binaries, but how can I get MAUI to reference the x64 one if it's building the simulator?  I can't find a way in BasicMauiApp.csproj to conditionally specify the right project reference for the simulator case.  Maybe it's not that hard?  Maybe there's an easy way that I'm missing to modify the condition below to handle the simulator case and reference the x64 version of Counter.iOS:

`<ItemGroup Condition="'$(TargetFramework)'=='net7.0-ios' Or '$(TargetFramework)'=='net7.0-maccatalyst'">
  <ProjectReference Include="..\Counter.iOS\Counter.iOS.csproj" />
</ItemGroup>`

Otherwise I get this error:

`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
ld: warning: ignoring file /Users/wes.hodges/Projects/bindingsample/BasicMauiApp/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/libCounteriOS.a, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture x86_64:
  "_CreateCounter", referenced from:
     -u command line option
  "_DeleteCounter", referenced from:
     -u command line option
  "_GetCount", referenced from:
     -u command line option
  "_SetCount", referenced from:
     -u command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (BasicMauiAppMac)`

**Comment by rolfbjarne** [comment]
> My Macbook has versions 16.2.19 and 16.2.1024 of Microsoft.iOS.Sdk in `/usr/local/share/dotnet/packs/`. I've tried to getversion 16.2.1007 via Nuget in Visual Studio for Mac by adding it as a package to Counter.iOS, but when I do I get a `Package 'Microsoft.iOS.Sdk 16.2.1007' has a package type 'DotnetPlatform' that is not supported by project 'Counter.iOS'`. Is there some other way I can get that Nuget package on my Macbook? I'm not especially Macbook savvy.

The simplest solution here is probably to install the exact same version of .NET on both Windows and Mac, and then build your project first on Mac, and then on Windows (both using the command line). When building on Mac, you'll be told which commands to execute to install the corresponding workloads. Once it's building on your Mac, it should have the correct versions installed to build remotely from Windows too.

> Second, do I ultimately need both an ARM64 and an x64 build of libCounteriOS.a?

Yes, and it's a bit complicated.

What you need is a universal (fat) archive, which contains both your arm64 version and your x64 version of libCounteriOS.a. You can do this with the `lipo` tool:

```shell
$ lipo -create path/to/arm64/libCounteriOS.a path/to/x64/libCounteriOS.a -output libCounteriOS.a
```

and then use the resulting library for both device and simulator builds.

However, going forward, you might need to add an arm64 version for the simulator (which is not the same as arm64 for device), and you'll run into a limitation in the universal archive: it doesn't support multiple versions of the same architecture, but for different platforms. Apple has a solution for this, called XCFrameworks: https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle, but unfortunately we have a few bugs related to xcframeworks when building from Windows, so it probably won't work until later this year (think .NET 8).

**Comment by whodges** [comment]
Thanks!  The `lipo` solution helped, though I'm still running into x86_64 errors with the maccatalyst build (which I've just disabled for now - the iOS one works).  Not too worried about this; I expect I'll need to go the xcframework route anyway given what you've described.

Regarding my Microsoft.iOS.Sdk 16.2.1007 error, building the project on the Mac first didn't help (I had tried that yesterday too), however, I ended up updating both the Windows and Mac instances of VS to the new 17.6 preview, and that gave me the MAUI workflows that use Microsoft.iOS.Sdk 16.2.1024.  This has got me further in the command line build approach, but it still fails with an error I don't understand:

`"C:\Projects\bindingsample\BasicMauiApp\BasicMauiAppMac.csproj" (default target) (1) ->
"C:\Projects\bindingsample\BasicMauiApp\BasicMauiAppMac.csproj" (Build target) (1:2) ->
"C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj" (default target) (2:8) ->
(_GenerateBindings target) ->
  C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1024\tools\msbuild\iOS\Xamarin.Shared.targets(1647,3): error : The file '/Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/BasicMauiAppMac/867bcbfb5d15e379f3d1c340349080f2bc3ee292c9c03964d47150577966a957//Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/BasicMauiAppMac/867bcbfb5
d15e379f3d1c340349080f2bc3ee292c9c03964d47150577966a957/obj/Debug/net7.0-ios/iOS/ObjCRuntime/Messaging.g.cs' was not found on the Server [C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj::TargetFramework=net7.0-ios]`

But when I went and checked on the Macbook to see if `Messaging.g.cs` exists, it did indeed get created during the build process and was there.  Not sure if there's a build timing issue.  I blew away the Xamarin cache folder and tried again with the same result.  I uploaded the binlog if it's of interest, and I'll poke at it more at this tomorrow.

**Comment by rolfbjarne** [comment]
> error : The file '/Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/BasicMauiAppMac/867bcbfb5d15e379f3d1c340349080f2bc3ee292c9c03964d47150577966a957//Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/BasicMauiAppMac/867bcbfb5 d15e379f3d1c340349080f2bc3ee292c9c03964d47150577966a957/obj/Debug/net7.0-ios/iOS/ObjCRuntime/Messaging.g.cs' was not found on the Server [C:\Projects\bindingsample\Counter.iOS\Counter.iOS.csproj::TargetFramework=net7.0-ios]

The problem is that the filename is wrong (there's full path appended to another path), although that's weird, this type of binding projects should work just fine from Windows.

**Comment by whodges** [comment]
You're right.  Just before line 1647 in Xamarin.Shared.targets, I see:

`<ItemGroup>
  <_DecompressedAppleBindingResourcePackage Include="@(_CompressedAppleBindingResourcePackage -> '$(_IntermediateDecompressionDir)/%(Filename)')" />
</ItemGroup>`

Could, say, `Filename` be set to a longer path than expected?

**Comment by rolfbjarne** [comment]
> You're right. Just before line 1647 in Xamarin.Shared.targets, I see:
> 
> `<ItemGroup> <_DecompressedAppleBindingResourcePackage Include="@(_CompressedAppleBindingResourcePackage -> '$(_IntermediateDecompressionDir)/%(Filename)')" /> </ItemGroup>`
> 
> Could, say, `Filename` be set to a longer path than expected?

I figured this out, and you seem to be running into all our bugs :/

In this case, I believe the bug is that we run into problems when building multiple projects (where one project depends on another).

This shows up in the build log with different SessionId values:

> SessionId = 4d19a3db64c3ddf6654c92c7086342fa6dab63a974b36645d1f7906594c825b0
> ...
> [xma][info]: Downloading /Users/wes.hodges/Library/Caches/Xamarin/mtbs/builds/BasicMauiAppMac/867bcbfb5d15e379f3d1c340349080f2bc3ee292c9c03964d47150577966a957/obj/Debug/net7.0-ios/iOS/sources.list...

(in this case the SessionId is part of the path, 867...)

So the question is: if you clean your solution, and build _just_ the binding project (and not the solution, nor the project referencing the binding project), does the build work?

**Comment by whodges** [comment]
Yes!  `dotnet build Counter.iOS/Counter.iOS.csproj /p:ServerAddress=[ip] /p:ServerUser=[user] /p:ServerPassword=[pw] /bl:msbuild.binlog` was successful.

**Comment by whodges** [comment]
Also, subsequently building BasicMauiApp.csproj is successful, however, it only seems to build iossimulator-x64.  Is there a way to get it to build ios-arm64?  And is there a command line call I can make to deploy the built solution to my phone?  If I use the IDE to deploy, it seems to rebuild the MAUI project and I get the VS Windows build of Counter.iOS rather than the remote build.  I'm assuming if I play around with `dotnet publish` I'll find something that works?

**Comment by rolfbjarne** [comment]
> it only seems to build iossimulator-x64. Is there a way to get it to build ios-arm64?

We default to `iossimulator-x64`. If you want to target `ios-arm64`, you can do this from the command line:

```shell
$ dotnet build /p:RuntimeIdentifier=ios-arm64
```

or alternatively add this to the project file:

```xml
<PropertyGroup>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>
```

> And is there a command line call I can make to deploy the built solution to my phone?

No, on Windows there's no way to deploy to your phone (from a Mac it's possible if you're interested).

> If I use the IDE to deploy, it seems to rebuild the MAUI project and I get the VS Windows build of Counter.iOS rather than the remote build.

You could try referencing the Counter.iOS.dll assembly directly in your MAUI project (as opposed to the Counter.iOS project). That way you'll use whatever you built earlier.

**Comment by whodges** [comment]
Ok, I did try simply referencing the Counter.iOS dll binary that I built via the command line with the mac parameters, and it doesn't work either.  So, neither the Counter.iOS assembly I built using VS for Mac on the Macbook itself, nor the Counter.iOS assembly I built via the command line worked in VS for Windows.

However, I then made the Counter.iOS assemblies I built using VS Windows my prebuilt binaries, and built BasicMauiApp on VS Mac with those Windows builds referenced instead of Counter.iOS.csproj.  And it worked.

It seems to be then that the only difference then re. Counter.iOS working or not is where BasicMauiApp.csproj is built and deployed from.  Build/deploy via VS Windows:  doesn't work.  Build/deploy via VS Mac:  works.  Perhaps it's not in the build, but in the deployment?  There are subtle differences in the BasicMauiApp\bin\ios-arm64 between VS Windows and VS Mac.  Also, the VS Mac build of BasicMauiApp gives me slight differences in the appearance of the app on my phone.  For example, the ".NET" text on the loading splash screen for the app is quite large when I build/deploy vis VS Windows, while it's rather small when I build/deploy via VS Mac.

Just trying to get to the bottom of this because I'd love to use VS Windows exclusively.

**Comment by rolfbjarne** [comment]
> Just trying to get to the bottom of this because I'd love to use VS Windows exclusively.

Note that if your project references a static library, the project must be built on a Mac (remotely if you're using Windows), because we use Xcode's toolchain to compile the static library into the final native executable.

The "Hot Restart" mode on Windows, where the build occurs exclusively on Windows, does not support static libraries: https://learn.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart#limitations

**Comment by whodges** [comment]
Got it.  And if I build remotely on my Mac using VS Windows, I have no way to deploy that specific build to my phone.

Ok, I appreciate all the help you've given me!  I don't think I have any other questions.

**Comment by rolfbjarne** [comment]
OK, I'm going to close this, since I believe have issues for any of the problems you ran into:

* Missing xcframework support on Windows: https://github.com/xamarin/xamarin-macios/issues/16571
* Trying to link a static library when using Hot Restart: https://github.com/xamarin/xamarin-macios/issues/17418
* The issue with build failures when building multiple projects has been fixed, and should be in the next VS version (17.6).

Thanks a lot for your patience!

**Comment by whodges** [comment]
My apologies, I have one last question, assuming I can still add to this thread:  is it possible to break into these native libraries using the VS debugger?  I can't find much online for MAUI on this.  I've been trying to keep it simple by just focusing on Windows and breaking into the exported SetCount call, which meant:

1. Ensured CounterWindows.pdb is copied to the relevant output directories.
2. Added a project debug profile via Properties->Debug for the MAUI project, where I check 'Enable native code debugging'.
3. Select that debug profile from the debug dropdown in VS Windows.  It stays selected for a couple seconds, but then jumps back to 'Windows Machine'.  Debugging doesn't let me step into my p/invoked native calls.

**Comment by rolfbjarne** [comment]
> is it possible to break into these native libraries using the VS debugger?

No, we don't support debugging native code with VS, you'd have to do that on the Mac, using either `lldb` from the command line or Xcode.
