### ISSUE TITLE
Windows: files in the .nuget cache replaced with empty files

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18348]
Symptom:

> error MT7091: File 'C:/Users/patri/.nuget/packages/devexpress.maui.controls/22.2.6/lib/net7.0-ios15.4/DevExpress.iOS.Navigation.resources/DXNavigation.xcframework/ios-arm64/DXNavigation.framework/DXNavigation' is not a valid framework: Unable to read beyond the end of the stream.

The problem is that the file in the error message is an empty file. Something in our build logic is wrong causing this behavior, but it's not trivial to find out what because it may have happened in a previous build.

Workaround: Delete the nuget cache (typically `C:\Users\{YourUser}\.nuget\packages`)

**Comment by bradyguyc** [comment]
I have an azure pipeline that built my app in release mode on 5/27 without a problem.  I tested this morning and it also built just fine on 6/6.  However, it will not build in visual studio 2022 preview in release or debug config.  Will not build with simulator or remote physical device.  Working on developing a small repo to see if I can reproduce.

**Comment by bradyguyc** [comment]
Sorry, yes you do have to build to see the error.  You don't have to add the devexpress component in xaml.   Just create a new project with the maui teamplate that gives you the bot and click button.   Add the devexpress component in nuget.   Then select the ios framework, select a simulator and build.   Then you get the error. 

I am building on windows.

**Comment by bradyguyc** [comment]
The repo that I provided above I tried to build on my mac mini.   However, something was off and I was getting a weird error related to project.assets.json and the colors.xml file.   So I just created a new mac project and added the devexpress component there.   It build and ran without a problem.  So seems to be an issue specific to the windows version visual studio.

**Comment by dk-mushiyoke** [comment]
I recall running into this issue with ios firebase nugets (xamarin.firebase.ios.*) when upgraded from vs 17.5.5 to 17.6.2 and vs would complain that the native frameworks being 0 bytes in size, but only when restoring inside visual studio. My solution was to 1. enable long directory path in registry, 2. clear out nuget cache then 3. run `dotnet restore` and 4. change the firebase cache folders to readonly, which worked for a while until I run into #18308 yesterday.

**Comment by bradyguyc** [comment]
I was able to get my large app to build on a mac with out this issue.   So it appears to be a windows visual studio problem only.   For me it works on mac, works on an azure pipeline (which is mac based so that makes sense).

**Comment by brunck** [comment]
I suspect this is related to the 260 char max path in VS for Windows. I've seen empty files related to that.

**Comment by bradyguyc** [comment]
This appears to be resolved with either updating the max char path or the latest version of vs.  Version 17.7.0 Preview 2.0 will build my app in debug on physical device with out the above problem with devexpress components.   However, with a simulator I am getting a new error with the linker where appcenter components will not link in for a simulator.   On to the next build problem :)

**Comment by marktopley** [comment]
The file being replaced for me is "C:\Users\Mark\.nuget\packages\xamarin.facebook.loginkit.ios\12.2.0.1\lib\net6.0-ios15.4\Facebook.LoginKit.resources\FBSDKLoginKit.xcframework\ios-arm64_armv7\FBSDKLoginKit.framework\FBSDKLoginKit" which is not 260 chars. Neither are any other files in that folder. As for you I'm able to continue working on VS for mac until a working release for windows.

**Comment by bradyguyc** [comment]
It works fine for me on my mac visual studio preview 2022 environment.   It also appears to work on windows visual studio 2022 preview 17.7.0 preview 2.   My app is not working with this version but it's related to a link issue with an appcenter component.  The zero byte issue with devexpress seems to have been resolved.

**Comment by jason-apj** [comment]
@rolfbjarne [https://github.com/dotnet/maui/issues/16886](url)

**Comment by jason-apj** [comment]
@rolfbjarne [https://github.com/dotnet/maui/issues/16886](url)
[Build.binlog.txt](https://github.com/xamarin/xamarin-macios/files/12492287/Build.binlog.txt)
Regarding this issue, this is my error log, see if it can be helpful。
I tried to clear Nuget again, but the result was still the same and an error was reported。

**Comment by rolfbjarne** [comment]
> @rolfbjarne [dotnet/maui#16886](https://github.com/dotnet/maui/issues/16886) [Build.binlog.txt](https://github.com/xamarin/xamarin-macios/files/12492287/Build.binlog.txt) Regarding this issue, this is my error log, see if it can be helpful。 I tried to clear Nuget again, but the result was still the same and an error was reported。

I've looked at the build log, and as far as I can tell it doesn't contain what we need to figure this out :/

**Comment by jason-apj** [comment]
> > @rolfbjarne [dotnet/maui#16886](https://github.com/dotnet/maui/issues/16886) [Build.binlog.txt](https://github.com/xamarin/xamarin-macios/files/12492287/Build.binlog.txt) Regarding this issue, this is my error log, see if it can be helpful。 I tried to clear Nuget again, but the result was still the same and an error was reported。
> 
> I've looked at the build log, and as far as I can tell it doesn't contain what we need to figure this out :/

Do you need to upload logs of all projects under the solution~

**Comment by rolfbjarne** [comment]
> > > @rolfbjarne [dotnet/maui#16886](https://github.com/dotnet/maui/issues/16886) [Build.binlog.txt](https://github.com/xamarin/xamarin-macios/files/12492287/Build.binlog.txt) Regarding this issue, this is my error log, see if it can be helpful。 I tried to clear Nuget again, but the result was still the same and an error was reported。
> > 
> > 
> > I've looked at the build log, and as far as I can tell it doesn't contain what we need to figure this out :/
> 
> Do you need to upload logs of all projects under the solution~

We've added logging that should make this obvious, but that won't be released until .NET 8. Until then, the build logs are likely to be rather useless, because they don't explain when these files got replaced with empty content.

What could help is if you have a reliable way to reproduce the problem, say something like:

1. Clean the NuGet cache on both Windows and Mac.
2. Build project X in Visual Studio on Windows - and it fails immediately.

And then provide us with project X + complete version information for Visual Studio.

**Comment by rolfbjarne** [comment]
We've gotten no reports about this for years now, so it seems this problem disappeared.
