### ISSUE TITLE
Maui-Firebase.Cloudmessage.SharedInstance is always null (window pc)

### ISSUE THREAD

**Issue by gabsamples6** [xamarin/xamarin-macios#19182]
@rolfbjarne   
As requested I have created this new issue and attached a noddy project - I could not put the original entitlements etc.. so if you could replace those as mentioned below that would be great..  

The main purpose of this issue is to prove that SharedInstance is always null when running on a windows pc. Hopefully I am missing the obvious..

Many thanks

### Steps to Reproduce

1. Windows pc with iPhone attached via usb.
2. Unzip the attached project
3. replace the Entitlement.plist and googleService-info.plist with yours
4. replace the App Identifier to match yours in csproj.
5. Build the project again.
6. Run the project
7. Press register button
8. there are 2 lines of code
    Firebase.Core.App.Configure();    
     Messaging.SharedInstance.AutoInitEnabled = true;
9. SharedInstance is always null when running the app from a phisycal iPhone device attached to a win 11 PC.

Note - it will compile once the correct entitlement.plist and  googleService-info.plist have been replaced.

I get
![image](https://github.com/xamarin/xamarin-macios/assets/109357537/8e44c59e-25ff-46cf-a0ea-bb70e591ee95)

 
![image](https://github.com/xamarin/xamarin-macios/assets/109357537/b508fb99-4664-486e-b491-be67b16b3322)

### Expected Behavior
SharedInstance should not be null
### Actual Behavior
SharedInstance should is null
### Example Project (If Possible)
[MauiPushiOS.zip](https://github.com/xamarin/xamarin-macios/files/12882333/MauiPushiOS.zip)

**Comment by TedMobile** [comment]
Hi
I have been trying to do some push notification and I cannot go any further on iOS because of this issue, I believe this is a long standing issue and I think people overcome it using a MAC but I dont have a mac and I use a window PC for development too.

just in 5 mins I have found these issue all related to SharedInstance being null, none of the possible workaround suggested works

https://github.com/xamarin/GoogleApisForiOSComponents/issues/621
https://github.com/xamarin/GoogleApisForiOSComponents/issues/486
https://stackoverflow.com/questions/76677155/messaging-sharedinstance-delegate-this-is-null-in-xamarin-ios


Can someone please have a look and tell us what are we doing wrong? 
@rolfbjarne @dalexsoto  sorry for tagging but we cannot set up push notification for iOS and it s become critical as it is key feature and we cannot debug or set up notification using a PC and an iPhone plugged into pc.

Many thanks

**Comment by rolfbjarne** [comment]
I can reproduce this, I'll see what we can do.

**Comment by gabsamples6** [comment]
@rolfbjarne  that would be a game changer for us..  I just hope you can find some time to fix this. thanks!

**Comment by rolfbjarne** [comment]
I think I've been able to fix this, but I'm not sure we'll be able to get all the fixes (there were quite a few) into the first .NET 8 release. If not, we'll include them in a service release.

**Comment by gabsamples6** [comment]
oh that is great news that you have fix!!!!  To get them in .net 8 GA would be fantastic and enable us to promote push notification to our clients for MAUI - we are kind of holding on what to say as we dont have a working solution.

Regardless we totally  appreciate any updates you might give us  -

**Comment by rolfbjarne** [comment]
Closing, this is fixed and it looks like we'll get it in .NET 8.

**Comment by gabsamples6** [comment]
That’s brilliant thanks for sorting for fixing this

**Comment by gabsamples6** [comment]
@rolfbjarne just tested on the latest .net 8 rtm and SharedInstance is still null. Is this the case at your end?

We cannot move on with push notification till this is sorted. Many thanks in advance

**Comment by Mercally** [comment]
Is this related to Google.SignIn.SignIn.SharedInstance ? I'm getting NullReferenceException on that field. Using NET MAUI 8, testing on iOS 17.0.1 Any idea?

**Comment by gabsamples6** [comment]
@rolfbjarne could this be looked at and reopened as it’s still an issue? Thanks

**Comment by rolfbjarne** [comment]
I'll have a look

**Comment by gabsamples6** [comment]
@rolfbjarne  hi grateful for some news on this one. Notifications is one of the most important features of the app and I hope that by setting the milestone to .net 9 we do not have to wait till then .  

Any chance of a fix with  next SR maui release?

**Comment by rolfbjarne** [comment]
I can't reproduce this with .NET 8, the SharedInstance property is not null now.

Can you get a binlog as described here and attach it to this issue: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs?

**Comment by gabsamples6** [comment]
@rolfbjarne  YES. it works and its no longer null!! thank you!!!
