### ISSUE TITLE
Xcode 10: list of changes to be reviewed/reverted before final release

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4189]
- [x] Workaround for rdar://40824310: [[mtouch] Work around build problem with Apple's simd headers in Objective-C++ mode.](https://github.com/xamarin/xamarin-macios/pull/4179/commits/390052703f254c9ebdf6ae5007d5e87bedd915c5) **Fixed: [Use libc++ instead of stdlibc++ when compiling with Xcode 10.](https://github.com/xamarin/xamarin-macios/commit/0d317207702d33cf78cf10d9a56adcda18d68329)**
- [x] Workaround for rdar://40824697: [[mtouch] Work around broken tvOS headers in Xcode 10 beta 1](https://github.com/xamarin/xamarin-macios/pull/4179/commits/663eaeb3898c8a0be87ee0797f96504a01cee740) **Fixed: [Revert "[mtouch] Work around broken tvOS headers in Xcode 10 beta 1."](https://github.com/xamarin/xamarin-macios/pull/4502)**
- [x] monotouch-tests disabled test cases (to review) https://github.com/xamarin/xamarin-macios/pull/4179/commits/07f79ac57d7f9746063ac2303a548c81d3a51ee9
    - [x] AVFoundation/CaptureDeviceTest.cs **Fixed: https://github.com/xamarin/xamarin-macios/pull/4655**
    - [x] AVKit/PlayerViewControllerTest.cs **Fixed: https://github.com/xamarin/xamarin-macios/pull/4656**
    - [x] CoreGraphics/FunctionTest.cs **Fixed: [[CoreGraphics] Fix CGFunction to work after being disposed.](https://github.com/xamarin/xamarin-macios/pull/4644)**
    - [x] CoreImage/FilterTest.cs **Fixed: https://github.com/xamarin/xamarin-macios/pull/4651**
- [x] new core image filters are only stubbed right now - [up to date with beta 4](https://github.com/xamarin/xamarin-macios/pull/4513) (minus open issues)
- [x] some old core image filters were removed - fixed in b4, tests re-enabled with c19710269fbb76c82f6e8eac19f1f0c283cb17fd
- [x] some GameKit selector don't respond anymore - need verification (then radar) **Fixed: [[Gamekit] Re-enable introspection tests in the skipped selectors.](https://github.com/xamarin/xamarin-macios/pull/4682)**
- [x] Workaround for rdar://41119081: [[msbuild] Ignore tests](https://github.com/xamarin/xamarin-macios/pull/4224/commits/e11c0019b9f44aceefbb101dcb48a2c8399c8892) fixed by bumping mono (_bad_ call conv) with https://github.com/xamarin/xamarin-macios/pull/4514
- [x] CMMovementDisorderManager is available on sim and [CMMovementDisorderManager.h](https://github.com/xamarin/xamarin-macios/pull/4247/files#diff-d1b72670ae4b703129861e7fc1d91a23) is added to CoreMotion's umbrella header - fixed in beta 4 (maybe earlier)
- [ ] `RPSystemBroadcastPickerView` is **not** [available on sim](https://github.com/xamarin/xamarin-macios/pull/4249/files#r195288042) still failing with Xcode GM
- [x] The `!WATCH` check from `src/Intents/INPlayMediaIntentResponse.cs` must be removed once `MediaPlayer` is enabled on the watch. Fixed with https://github.com/xamarin/xamarin-macios/pull/4505
- [ ] [introspection] CMMovementDisorderManager isn't usable for now: #4306.
- [x] The macOS version was bumped to 10.9 during the Xcode 10 beta 4 bump to keep things working ([trello](https://trello.com/c/PsHpNHq6/113-40824697-scenekith-doesnt-compile-as-objective-c#comment-5b4f5bad078b4a35c15b8b58)) **Fixed: [Use libc++ instead of stdlibc++ for Xamarin.Mac too](https://github.com/xamarin/xamarin-macios/pull/4501)**
- [X] rdar://41335393: [ARKit] Removed NSCopying protocol conformance on ARReferenceImage. -> **Apple said it is by design. We did not remove the protocol conformance as it would be a breaking change.**
- [X] rdar://41647370: HMHome removeUser:completionHandler: is now prohibited on iOS? Typo? -> **Fixed [[homekit] Remove export for 'RemoveUser' (iOS prohibited)](https://github.com/xamarin/xamarin-macios/pull/4542)**  
- [ ] [rdar://41123682](https://trello.com/c/Eyox7vlH): TVElementUpdateType* enum values changed.
- [ ] [rdar://43425168](https://trello.com/c/dtVv2a6R): IN*WorkoutIntentResponseCode enum values changed.

**Comment by VincentDondain** [comment]
[] rdar://41335393: [[ARKit] Removed NSCopying protocol conformance on ARReferenceImage](https://trello.com/c/F7bjcplW/121-41335393-arkit-removed-nscopying-protocol-conformance-on-arreferenceimage).

**Comment by spouliot** [comment]
@VincentDondain (and all) please edit the main content as it shows, in the project, how many of the items are fixed (and we do not want to close this while some other items, in descriptions, are missed). IOW comments are fine, but the `[ ] ...` should be in the top comment. Thanks!

**Comment by mandel-macaque** [comment]
Tested  AVFoundation/CaptureDeviceTest.cs on Xcode10-beta6, it has no been yet fixed AFAIK.

**Comment by mandel-macaque** [comment]
Tested the adding com.apple.developer.health-movement-disorder (from the release notes) to the templates/WatchContainer/Entitlements.plist which theoretically should fix the issue, yet the apple crashes, [diff of my changes](https://gist.github.com/mandel-macaque/7f85b54edfcef0c8c17bbc9ae981b266)

Was tested with Xcode 10 beta 6.

**Comment by mandel-macaque** [comment]
Reconfirming that the CMMovementDisorderManager continues to crash the introspection tests on the watch, I followed @spouliot comment of adding NSMotionUsageDescription the the info.plist ([see diff](https://gist.github.com/mandel-macaque/c2982f5e95a5d3c3c4aff58d8b91fe9f)) and the issues continues on Xcode 10 beta 6.

**Comment by mandel-macaque** [comment]
GameKit selectors got fixed, PR re-enabling the tests can be found here: https://github.com/xamarin/xamarin-macios/pull/4682

**Comment by spouliot** [comment]
*RPSystemBroadcastPickerView is not available on sim* seems o work on GM

**Comment by spouliot** [comment]
2018-09-13 11:58:02.332507-0400 introspection[34682:983190] [Health] {"msg":"Usage of CMMovementDisorderManager requires a special entitlement.  Please see for more information https://developer.apple.com/documentation/coremotion/cmmovementdisordermanager", "event":assert, "condition":isEntitled}

still happens - but there's now a web page to request the entitlement

**Comment by spouliot** [comment]
CMMovementDisorderManager with an Entitlement.plist seems to work locally, might need some adjustment to xharness - but introspection is happy

**Comment by spouliot** [comment]
Remaining issues moved to Xcode 10.1 rdar tracking
