### ISSUE TITLE
PHObject -> PHAsset cast failure with iOS 13 SDK

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#6695]
The following piece of code in our app, Seeing AI, has been working for some time and was fine with iOS 12 SDK, but results in a null photoObject with iOS 13 SDK:

```csharp
PHPhotoLibrary.RequestAuthorization (s => Console.WriteLine ($"Request status: {s}"));

PHFetchResult assets = PHAsset.FetchAssets (PHAssetMediaType.Image, null);
foreach (PHAsset photoObject in assets) {
	Console.WriteLine ();
}
```

The same cast does work in XCode and swift with the new SDK, but fails in Xamarin.

**Comment by dalexsoto** [comment]
I am able to reproduce this issue:

```
System.InvalidCastException: Specified cast is not valid.
  at phphotobug.ViewController.ViewDidLoad () [0x00040] in phphotobug/phphotobug/ViewController.cs:20
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in xamarin-macios/src/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in xamarin-macios/src/UIKit/UIApplication.cs:65
  at phphotobug.Application.Main (System.String[] args) [0x00001] in phphotobug/phphotobug/Main.cs:10
```

[phphotobug.zip](https://github.com/xamarin/xamarin-macios/files/3453632/phphotobug.zip)

**Comment by dalexsoto** [comment]
As a workaround have the following class added to your project

```csharp
using System;
using System.Runtime.InteropServices;
using Foundation;
using ObjCRuntime;
using Photos;
```

```csharp
public static class PHFetchResultExtensions {
	[DllImport (Constants.ObjectiveCLibrary, EntryPoint = "objc_msgSend")]
	extern static IntPtr IntPtr_objc_msgSend_nint (IntPtr receiver, IntPtr selector, nint arg1);

	public static T GetAsset<T> (this PHFetchResult result, nint index) where T : NSObject
	{
		return Runtime.GetNSObject<T> (IntPtr_objc_msgSend_nint (result.Handle, Selector.GetHandle ("objectAtIndexedSubscript:"), index));
	}
}
```

Usage:

```csharp
PHFetchResult assets = PHAsset.FetchAssets (PHAssetMediaType.Image, null);

var count = assets.Count;
for (int i = 0; i < count; i++) {
	var photoObject = assets.GetAsset<PHAsset> (i);
	// do something with photoObject
}
```

**Comment by yevgeniy-seleznev** [comment]
Thanks Alex -- confirmed the workaround works as expected.

**Comment by rpendleton** [comment]
I can confirm that the workaround works for me as well.

@dalexsoto Is this something that can (/will) be fixed in the Xamarin bindings in the near future, or should I plan on including this workaround long term? I'm not incredibly familiar with the release cycle of Xamarin.iOS, but given that iOS 13 will likely be released in a few weeks, it seems like a fix for this would be good to have in Xamarin.

**Comment by rolfbjarne** [comment]
@rpendleton we'll look at getting it fixed with the release that supports Xcode 11 and iOS 13 (which would come out very soon after they go to stable), but we can't guarantee anything until we've had a deeper look and figured out an actual fix.

**Comment by rolfbjarne** [comment]
@dalexsoto this works for me on both device (with iOS 13.1 beta 1) and simulator (iOS 13.0 b7).

Could you check again and see if it works for you too? Maybe Apple changed something in iOS so that we don't have to fix anything after all.

**Comment by rpendleton** [comment]
@rolfbjarne Are you testing with a build made using the iOS 13 SDK? The ticket I logged internally for my work indicates that this was occurring on iOS 13.0 b8, but only when built with the iOS 13 SDK that's available from the Xcode 11 update channel. When I get some time later today, I can test with the newest version of the Xcode 11 preview.

**Comment by rpendleton** [comment]
@rolfbjarne I'm still seeing the issue. Here's some information about my environment:

Visual Studio for Mac: 8.2.4 (build 45)
Xcode 11.0 beta 7 (11M392r)
Xamarin.Mac 5.99.3.5
Xamarin.iOS 12.99.3.5
Mono Framework MDK: 6.0.0.327
macOS 10.14.6

**Comment by dalexsoto** [comment]
Using https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/0b4fc12f322c6660a9a0636776edc9dd233bc7d5/287/package/xamarin.ios-12.99.4.40.pkg I do not see this issue anymore. I think we fixed this @rolf aster xamarin.ios-12.99.4.21.pkg so this is why @rpendleton saw this.

Closing this as I am not able to repro this anymore. Please re-open if needed.

**Comment by rpendleton** [comment]
I can confirm that this issue no longer occurs after updating to Xamarin.iOS 12.99.4.26.

**Comment by dalexsoto** [comment]
Excellent, thank you!!
