### ISSUE TITLE
Release build of Xamarin MacOS app (Xamarin.Forms) fails the Verify process of Apple's Transport.app

### ISSUE THREAD

**Issue by baskren** [xamarin/xamarin-macios#9076]
Short Description:

Release build of Xamarin MacOS app (Xamarin.Forms) fails verify process of Apple's Transport.app with the following issue:

> ERROR ITMS-90283: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.myOrg.myApp [com.myOrg.myApp.pkg/Payload/myApp.Mac.app] is invalid. [Invalid 'com.apple.application-identifier' entitlement value.]

<img width="618" alt="image" src="https://user-images.githubusercontent.com/2528888/87372723-455fff80-c556-11ea-9ebb-b265959dc1d6.png">

### Steps to Reproduce

1.  Create a Xamarin.Forms.Mac app and successfully run it in debug mode.
2. Follow steps shown in the following Xamarin.Mac documentation:
  - [Publishing Xamarin.Mac Apps to the Mac App Store](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/)
  - [Certificates and identifiers in Xamarin.Mac](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/certificates-identifiers)
  - [Provisioning profiles for Xamarin.Mac apps](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/profiles)
  - [Mac app configuration](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/app-configuration)
  - [Bundling for the Mac App Store](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/bundling)
3. Attempt to complete the documentation in [Upload to Mac App Store](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/uploading)
4. The last step of the above documentation is to use **Transporter** to upload the app.  Alternatively, you can attempt to *Verify* the app (using **Transporter**) and get the same results.

### Expected Behavior

The app is successfully verified

### Actual Behavior

With the above (and all of the additional steps, noted in **Diagnostics already tried**, below) **Transporter** fails verification with the following message:

> ERROR ITMS-90283: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.myOrg.myApp [com.myOrg.myApp.pkg/Payload/myApp.Mac.app] is invalid. [Invalid 'com.apple.application-identifier' entitlement value.] For more information, visit the macOS Developer Portal."

##### Info.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>AssetBuilder</string>
	<key>CFBundleIdentifier</key>
	<string>com.p42.AssetBuilder</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.15</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>NSHumanReadableCopyright</key>
	<string>42nd Parallel, 2020</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSMainStoryboardFile</key>
	<string>Main</string>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/AppIcon.appiconset</string>
	<key>CFBundleDisplayName</key>
	<string>AssetBuilder</string>
</dict>
</plist>
```

##### Entitlements.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-write</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
</dict>
</plist>
```

##### VisualStudio Project Settings / Mac Signing
![image](https://user-images.githubusercontent.com/2528888/87354393-804d3d80-c52c-11ea-9e1e-e1b6415c266e.png)

##### Apple App Connect / Certificates 
![image](https://user-images.githubusercontent.com/2528888/87354533-ae328200-c52c-11ea-9ae6-b258c70d181b.png)

![image](https://user-images.githubusercontent.com/2528888/87354624-da4e0300-c52c-11ea-9d90-fe0150432473.png)

##### Keychain / Certificates

![image](https://user-images.githubusercontent.com/2528888/87354712-049fc080-c52d-11ea-9f6f-6dabec865d59.png)

![image](https://user-images.githubusercontent.com/2528888/87354736-0ff2ec00-c52d-11ea-896a-0750c0e35d95.png)

##### Apple App Connect / Identities

![image](https://user-images.githubusercontent.com/2528888/87355651-b8ee1680-c52e-11ea-9ec8-2c4cfda07399.png)

NOTE: No capabilities on this page have been checked as they are not needed (nor listed in the Entitlements.plist, above).

##### Provisioning Profile

<img width="858" alt="image" src="https://user-images.githubusercontent.com/2528888/87372588-f5813880-c555-11ea-83ca-69760edddef3.png">

##### After Release Build, using [Max Inspect](https://apps.apple.com/us/app/max-inspect/id1438113612?mt=12)

![image](https://user-images.githubusercontent.com/2528888/87356129-885aac80-c52f-11ea-80dd-4fdc80e49e99.png)

![image](https://user-images.githubusercontent.com/2528888/87356084-7711a000-c52f-11ea-8979-c4bf3dcb39b5.png)

##### NOTES:

1. The `.pkg` file was pulled from the MacOS platform project folder's bin/Release/ folder
2. For use with **Max Inspector**, the `.app` was also pulled from the MacOS platform project folder's bin/Release folder
3. The Xamarin generated `com.apple.application-identifier` value is `2RS7Y3P527.com.p42.AssetBuilder`.  Notice that the prefix is the App ID Prefix, not, KKD88FVWF5, the publisher's ID.
4. In VisualStudio / Project Settings / Mac Signing,  KeyChain, and in the .app file (via Max Inspect), the Certificates are the same: `Mac Distribution: 42nd Parallel (KKD88FVWF5)`

##### Additional step (for grins).  Use VisualStudio's **Archive for Publishing** and **[Sign and Distribute]**
In the below, the `.pkg` file was pulled from the destination chosen for publishing.

A) Sign and distribute as "Mac Installer Package"
![image](https://user-images.githubusercontent.com/2528888/87356441-133ba700-c530-11ea-994d-7c8700f405f6.png)

    Transporter gives the same result.

B) Sign and distribute as "App Store"

    Same as above

#### Using new **Apple Distribution** Certificate

If one were to create a new MacOS app using Xcode 11.5, that app would use the new Apple Distribution Certificate (instead of the Mac Distribution Certificate, as shown in the above section).  Also note that, in VisualStudio / Preferences / Publishing / Apple Developer Accounts ...

<img width="973" alt="image" src="https://user-images.githubusercontent.com/2528888/87374846-f49dd600-c558-11ea-9b6c-08d1f5692f34.png">

Only the new **Apple Distribution** certificate is shown - not that older **Mac Distribution** ... even though both can be found in App Connect: 
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/2528888/87375295-2adb5580-c559-11ea-9216-b800a0ece58c.png">

Below is an attempt to use this approach with VisualStudio.

##### VisualStudio Project Settings / Mac Signing

<img width="966" alt="image" src="https://user-images.githubusercontent.com/2528888/87372107-c3bba200-c554-11ea-9198-278f4bee690b.png">

Note that even though the Apple Distribution Certificate is in keychain (below) and shown in VisualStudio (above), it is not an option in Project Settings / App Signing.  However, as will be shown later, the default settings do use the Apple Distribution Certificate.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/2528888/87373145-1dbd6700-c557-11ea-8475-904dc80d253d.png">

##### Apple Distribution Certificate

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/2528888/87371828-27919b00-c554-11ea-8883-ec86985b81c5.png">

![image](https://user-images.githubusercontent.com/2528888/87354624-da4e0300-c52c-11ea-9d90-fe0150432473.png)

##### Keychain / Certificates

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2528888/87372405-768c0000-c555-11ea-8917-af691f6e73a9.png">
![image](https://user-images.githubusercontent.com/2528888/87354736-0ff2ec00-c52d-11ea-896a-0750c0e35d95.png)

##### Provisioning Profile

<img width="882" alt="image" src="https://user-images.githubusercontent.com/2528888/87372559-da162d80-c555-11ea-8407-2dda4c67ae75.png">

##### After Release Build, using [Max Inspect](https://apps.apple.com/us/app/max-inspect/id1438113612?mt=12)

<img width="762" alt="image" src="https://user-images.githubusercontent.com/2528888/87373253-54937d00-c557-11ea-9744-cf29efb78dc0.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/2528888/87373259-5cebb800-c557-11ea-89d5-814d2e7bfd16.png">

NOTE:  Here you can see that the app was built using the new Apple Distribution type of Certificate!

However, when trying to **Verify** using **Transporter**, the same error occurs.  And, when trying to use **Archive for Publishing** ...

##### Additional step (for grins).  Use VisualStudio's **Archive for Publishing** and **[Sign and Distribute]**

A) Sign and distribute as "Mac Installer Package"
<img width="647" alt="image" src="https://user-images.githubusercontent.com/2528888/87373558-e4392b80-c557-11ea-992d-a242e4c433b3.png">

B) Sign and distribute as "App Store"
<img width="647" alt="image" src="https://user-images.githubusercontent.com/2528888/87373558-e4392b80-c557-11ea-992d-a242e4c433b3.png">

Note that both approaches show the OLD **Mac Distribution** certificates for signer identity - not the new **Apple Distribution**.  And, as before, **Transporter** fails to verify the app.

### Yet to be tried:

- Manually try to sign the app and build the package.  Looks pretty involved so I might sit on this for a couple of days until I get any tangible feedback on this issue.

### Environment

```
NOTE THAT THIS ISSUE IS OCCURING ON BOTH THE STABLE AND PREVIEW VERSIONS OF VISUAL STUDIO

=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.7 Preview (8.7 build 1802)
Installation UUID: 11a1b772-61b7-4c9c-afa5-07031dfba761
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000074

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.74 (2020-02/e9d3af508e4) (64-bit)
	Package version: 612000074

=== Roslyn (Language Service) ===

3.7.0-3.20312.3+ec4841263590f5456e32728d98097e97c1605e22

=== NuGet ===

Version: 5.7.0.6653

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.301/Sdks
SDK Versions:
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Version: 6.20.1.18 (Visual Studio Community)
Hash: 8ffa3d888
Branch: d16-7
Build date: 2020-06-06 13:34:07-0400

=== Xamarin.iOS ===

Version: 13.20.1.18 (Visual Studio Community)
Hash: 8ffa3d888
Branch: d16-7
Build date: 2020-06-06 13:34:08-0400

=== Xamarin Designer ===

Version: 16.7.0.459
Hash: 65d9dd3aa
Branch: remotes/origin/d16-7
Build date: 2020-06-10 03:48:34 UTC

=== Xamarin.Android ===

Version: 10.4.0.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/de70286
Android SDK: /Users/benjaminaskren/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.3
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 87ef555
Java.Interop: xamarin/java.interop/d16-7@76d1ac7
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/benjaminaskren/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.8
Hash: 6e20e98
Branch: remotes/origin/d16-7
Build date: 2020-06-11 19:23:34 UTC

=== Android Device Manager ===

Version: 16.7.0.12
Hash: 51b7059
Branch: remotes/origin/d16-7
Build date: 2020-06-11 19:23:58 UTC

=== Build Information ===

Release ID: 807001802
Git revision: 2129f3002481c263b627ea82a6f25349ee5947cb
Build date: 2020-06-22 06:15:44-04
Build branch: release-8.7
Xamarin extensions: 2129f3002481c263b627ea82a6f25349ee5947cb

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
NuGet Package Explorer 0.5
NuGet Package Management Extensions 0.23
Open With 0.2
AddinMaker 1.5.0
MSBuild Editor 2.4.0


```

### Build Logs

https://gist.github.com/baskren/7f2a7c6e6e0c759033e8d90c19056a43

### Example Project (If Possible)

https://github.com/baskren/AssetBuilder

**Comment by jamesmontemagno** [comment]
I just released My Stream Timer via VSfM and went through this alright. It is really complicated because there is app store and non-app store installers.

So, for app store you should NOT check "sign the installer package"
![image](https://user-images.githubusercontent.com/1676321/87466331-f0120580-c5ca-11ea-8048-f35a138c08e1.png)

Also you don't need the hardened runtime if you are releasing to the store.

From there, I archive for publishing and do App Store for sign & distribute
![image](https://user-images.githubusercontent.com/1676321/87466579-60208b80-c5cb-11ea-8c21-2a209d54a60d.png)


From there you can do the normal flow and upload via transporter.
![image](https://user-images.githubusercontent.com/1676321/87466711-9958fb80-c5cb-11ea-9833-1d51e2ebd0c4.png)

**Comment by chamons** [comment]
Marking as need-info until we hear back.

**Comment by baskren** [comment]
@jamesmontemagno -  Thank you for the prompt response.  

Unfortunately, I could not get the above recommendation to work for me.  What I've tried as a result of that recommendation:

1.  I've tried a full set of permutations with both of the following **Project Settings / Mac Signing**

    ![image](https://user-images.githubusercontent.com/2528888/87468446-a4ba2000-c5e7-11ea-9c53-3a7abd75497a.png)

    ![image](https://user-images.githubusercontent.com/2528888/87468486-b69bc300-c5e7-11ea-8f43-031bc797e021.png)

2. Complete delete of 'bin/' and 'obj/' folders and restart of VSfM before each build

3. A full set permutations of Submitting to **Transporter** the  `.pkg` file from the following processes:

  - Build process (`.pkg` from the `bin/Release/` folder)
  - **Archive for Publishing** + **[Sign and Distribute]** + **App Store** process (`.pkg` from the folder chosen during **[Sign and Distribute]**)

In all cases, I get output like the following from **Transporter**:

    ![image](https://user-images.githubusercontent.com/2528888/87468909-6b35e480-c5e8-11ea-8d41-124113190e93.png)

**Verification Log**
```
[2020-07-14 15:33:22 EDT] <main>  INFO: Configuring logging...
[2020-07-14 15:33:22 EDT] <main>  INFO: Logging level set to eXtreme
[2020-07-14 15:33:22 EDT] <main>  INFO: Transporter is searching for new software components.
[2020-07-14 15:33:22 EDT] <main>  INFO: INFO: using cached repository.xml file.
[2020-07-14 15:33:22 EDT] <main>  INFO: Update check complete.
[2020-07-14 15:33:23 EDT] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[2020-07-14 15:33:23 EDT] <main> DEBUG: Configuration refresh successful.
[2020-07-14 15:33:23 EDT] <main> DEBUG: Saving configuration to local path: /Users/benjaminaskren/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
[2020-07-14 15:33:23 EDT] <main>  INFO: iTMSTransporter : iTunes Store Transporter [2.0.0]
[2020-07-14 15:33:23 EDT] <main>  INFO: OS identifier: Mac OS X 10.15.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2020-07-14 15:33:23 EDT] <main>  INFO: Memory: [JVM] 1045M free, 1101M total, 1820M max [System] (Physical) 48527M free, 65536M total (Swap) 0 free, 0 total
[2020-07-14 15:33:23 EDT] <main>  INFO: Client: TransporterApp 1.1.1 (1171)
[2020-07-14 15:33:23 EDT] <main>  INFO: Verify mode selected.
[2020-07-14 15:33:23 EDT] <main>  INFO: Examining the package at: /var/folders/83/_5ygzczj7wd39k52kr6_jdqr0000gn/T/809D92A8-FBD5-4BE0-9B1F-E034790ECFC6/1523219962.itmsp
[2020-07-14 15:33:23 EDT] <main>  INFO: Ensuring that package has well formed metadata file...
[2020-07-14 15:33:23 EDT] <main> DEBUG: Getting case-sensitive metadata xml filename...
[2020-07-14 15:33:23 EDT] <main>  INFO: Gathering the list of valid files from the package ...
[2020-07-14 15:33:23 EDT] <main> DEBUG:   AssetBuilder.pkg will be verified by Apple's web service to determine if it is a valid file.
[2020-07-14 15:33:23 EDT] <main> DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[2020-07-14 15:33:23 EDT] <main>  INFO: Finished gathering the list of valid files from the package.
[2020-07-14 15:33:23 EDT] <main> DEBUG:   Case-sensitive metadata filename is: metadata.xml
[2020-07-14 15:33:23 EDT] <main>  INFO: Performing verification of package 1523219962.itmsp...
[2020-07-14 15:33:24 EDT] <main> DBG-X: Memory: [JVM] 1043M free, 1101M total, 1820M max [System] (Physical) 48526M free, 65536M total (Swap) 0 free, 0 total
[2020-07-14 15:33:24 EDT] <main>  INFO: JSON:{"msg":{"phase":"Verify","description":"Analyzing metadata","index":0},"messageType":"VerifyProgress"}
[2020-07-14 15:33:24 EDT] <main> DBG-X: Deflated 615 bytes to 452
[2020-07-14 15:33:24 EDT] <main> DBG-X: Using operation named: validateMetadata
[2020-07-14 15:33:24 EDT] <main> DBG-X: Apple's web service operation input parameters:
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Application = iTMSTransporter
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter BaseVersion = 1.13.0
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Client = TransporterApp
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter ClientVersion = 1.1.1 (1171)
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter DryRun = true
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Files = [AssetBuilder.pkg, metadata.xml]
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter ItcProviderName = 42ndParallel
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
<package version="software5.4" xmlns="http://apple.com/itunes/importer">
    <software_assets apple_id="1523219962"
        bundle_short_version_string="1.0"
        bundle_version="1"
        bundle_identifier="com.p42.AssetBuilder"
        app_platform="osx">
        <asset type="product-archive">
            <data_file>
                <file_name>AssetBuilder.pkg</file_name>
                <checksum type="md5">fbed0aef9b6afebc25b0a8304d42d815</checksum>
                <size>30299044</size>
            </data_file>
        </asset>
    </software_assets>
</package>

[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter MetadataChecksum = 09f13db7a021167e5db1ce244d585a15
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter MetadataCompressed = (suppressed)
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.15.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter PackageName = 1523219962.itmsp
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter PackageSize = 30299659
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2020-07-14T15:33:24-04:00
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.12943803
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter TransporterArguments = -m verify -u myemailaddress@myemailprovider.com -vp json -sessionid @env:52BED9A3-E416-4B02-8B78-69880A01E2AF -sharedsecret **hidden value** -itc_provider 42ndParallel -f /var/folders/83/_5ygzczj7wd39k52kr6_jdqr0000gn/T/809D92A8-FBD5-4BE0-9B1F-E034790ECFC6/1523219962.itmsp -indicator true -v eXtreme -Dtransporter.client=TransporterApp -Dtransporter.client.version=1.1.1 (1171)
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Version = 2.0.0
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter iTMSTransporterMode = verify
[2020-07-14 15:33:24 EDT] <main>  INFO: id = 20200714153324-579
[2020-07-14 15:33:24 EDT] <main>  INFO: iTMSTransporter Correlation Key: 92947fa1-42ec-4043-b74a-4866141e9a47-0001
[2020-07-14 15:33:24 EDT] <main> DBG-X: Apple's web service operation return value:
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter SessionExpiration = 2020-07-18T19:33:24.265Z
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Success = true
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter FilesToUpload = [metadata.xml, AssetBuilder.pkg]
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=AssetBuilder.pkg, ShouldDescribeAsset=true, UTI=com.apple.pkg}]
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter CPUToken = 3ae203af-6cd6-4ee8-bddf-64e87e9135cb/1594755204639
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter Checksums = {AssetBuilder.pkg=fbed0aef9b6afebc25b0a8304d42d815}
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter FileSizes = {AssetBuilder.pkg=30299044}
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
[2020-07-14 15:33:24 EDT] <main> DBG-X:   parameter ProviderNameForToken = 42ndParallel
[2020-07-14 15:33:24 EDT] <main>  INFO: The asset replacement verification check is disabled.
[2020-07-14 15:33:24 EDT] <main>  INFO: Checking the file size of the files: [AssetBuilder.pkg]
[2020-07-14 15:33:24 EDT] <main> DBG-X:  Checking the size of file: AssetBuilder.pkg
[2020-07-14 15:33:24 EDT] <main>  INFO: Done checking the file sizes.
[2020-07-14 15:33:24 EDT] <main>  INFO: Checking the md5 checksum of the files: [AssetBuilder.pkg]
[2020-07-14 15:33:24 EDT] <main> DBG-X:  Checking the MD5 checksum of file: AssetBuilder.pkg
[2020-07-14 15:33:24 EDT] <main>  INFO: Done checking the md5 checksum.
[2020-07-14 15:33:24 EDT] <main>  INFO: Starting media analysis of assets
[2020-07-14 15:33:25 EDT] <main> DEBUG: Handling asset: filename=AssetBuilder.pkg,uti=com.apple.pkg,role=source,describe=true
[2020-07-14 15:33:25 EDT] <main>  INFO: JSON:{"msg":{"phase":"Verify","count":3,"description":"Adding asset to analyze:","index":1,"asset":"AssetBuilder.pkg"},"messageType":"VerifyProgress"}
[2020-07-14 15:33:25 EDT] <main> DEBUG: Using container type tool name and version: Mac App Describer:1.26
[2020-07-14 15:33:25 EDT] <main> DEBUG: Using path: /var/folders/83/_5ygzczj7wd39k52kr6_jdqr0000gn/T/809D92A8-FBD5-4BE0-9B1F-E034790ECFC6/1523219962.itmsp/AssetBuilder.pkg
[2020-07-14 15:33:26 EDT] <main> DBG-X: description length:0
[2020-07-14 15:33:26 EDT] <main> DBG-X: Asset description: 
[2020-07-14 15:33:26 EDT] <main> DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@78010562
[2020-07-14 15:33:26 EDT] <main> DBG-X: Deflated 538 bytes to 338
[2020-07-14 15:33:26 EDT] <main>  INFO: Asset media analysis has completed
[2020-07-14 15:33:26 EDT] <main> DBG-X: Memory: [JVM] 1010M free, 1101M total, 1820M max [System] (Physical) 48502M free, 65536M total (Swap) 0 free, 0 total
[2020-07-14 15:33:26 EDT] <main>  INFO: JSON:{"msg":{"phase":"Verify","count":3,"description":"Validating assets","index":2},"messageType":"VerifyProgress"}
[2020-07-14 15:33:26 EDT] <main> DBG-X: Deflated 615 bytes to 452
[2020-07-14 15:33:26 EDT] <main> DBG-X: Using operation named: validateAssets
[2020-07-14 15:33:26 EDT] <main> DBG-X: Apple's web service operation input parameters:
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter Application = iTMSTransporter
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter BaseVersion = 1.13.0
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter Client = TransporterApp
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter ClientVersion = 1.1.1 (1171)
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter DryRun = true
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter Files = [AssetBuilder.pkg, metadata.xml]
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter ItcProviderName = 42ndParallel
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter MetadataChecksum = 09f13db7a021167e5db1ce244d585a15
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter MetadataCompressed = (suppressed)
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.15.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter PackageName = 1523219962.itmsp
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter PackageSize = 30299659
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2020-07-14T15:33:26-04:00
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter StreamingInfoList = [file: 7052deb4-2294-4acc-a90d-9ea0d50e5b993953575701799083307.swinfo.plist.gz, content-length: 56447, content-type: application/binary, MD5: ebd259d727dd6a6ae16607a18291f202]
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter TransporterArguments = -m verify -u myemailaddress@myemailprovider.com -vp json -sessionid @env:52BED9A3-E416-4B02-8B78-69880A01E2AF -sharedsecret **hidden value** -itc_provider 42ndParallel -f /var/folders/83/_5ygzczj7wd39k52kr6_jdqr0000gn/T/809D92A8-FBD5-4BE0-9B1F-E034790ECFC6/1523219962.itmsp -indicator true -v eXtreme -Dtransporter.client=TransporterApp -Dtransporter.client.version=1.1.1 (1171)
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter Version = 2.0.0
[2020-07-14 15:33:26 EDT] <main> DBG-X:   parameter iTMSTransporterMode = verify
[2020-07-14 15:33:26 EDT] <main>  INFO: id = 20200714153326-961
[2020-07-14 15:33:26 EDT] <main>  INFO: iTMSTransporter Correlation Key: 92947fa1-42ec-4043-b74a-4866141e9a47-0001
[2020-07-14 15:33:28 EDT] <main> DBG-X: Apple's web service operation return value:
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter RestartClient = false
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter Success = false
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter Errors = [ERROR ITMS-90283: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.p42.AssetBuilder [com.p42.AssetBuilder.pkg/Payload/AssetBuilder.Mac.app] is invalid. [Invalid 'com.apple.application-identifier' entitlement value.] For more information, visit the macOS Developer Portal."]
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter FilesToUpload = [metadata.xml, AssetBuilder.pkg]
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=AssetBuilder.pkg, ShouldDescribeAsset=true, UTI=com.apple.pkg}]
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter Checksums = {AssetBuilder.pkg=fbed0aef9b6afebc25b0a8304d42d815}
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter FileSizes = {AssetBuilder.pkg=30299044}
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter ErrorCode = 1102
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter ErrorMessage = ERROR ITMS-90283: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.p42.AssetBuilder [com.p42.AssetBuilder.pkg/Payload/AssetBuilder.Mac.app] is invalid. [Invalid 'com.apple.application-identifier' entitlement value.] For more information, visit the macOS Developer Portal.
 (1102)
[2020-07-14 15:33:28 EDT] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
[2020-07-14 15:33:28 EDT] <main> ERROR: ERROR ITMS-90283: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.p42.AssetBuilder [com.p42.AssetBuilder.pkg/Payload/AssetBuilder.Mac.app] is invalid. [Invalid 'com.apple.application-identifier' entitlement value.] For more information, visit the macOS Developer Portal."
[2020-07-14 15:33:28 EDT] <main> DBG-X: The error code is: 1102
[2020-07-14 15:33:28 EDT] <main>  INFO: JSON:{"msg":{"phase":"Verify","count":3,"description":"Operation failed","index":3},"messageType":"VerifyProgress"}
[2020-07-14 15:33:28 EDT] <main> DBG-X: Returning 1




Package Summary:
 
1 package(s) were not verified because they had problems:
	/var/folders/83/_5ygzczj7wd39k52kr6_jdqr0000gn/T/809D92A8-FBD5-4BE0-9B1F-E034790ECFC6/1523219962.itmsp - Error Messages:
		ERROR ITMS-90283: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.p42.AssetBuilder [com.p42.AssetBuilder.pkg/Payload/AssetBuilder.Mac.app] is invalid. [Invalid 'com.apple.application-identifier' entitlement value.] For more information, visit the macOS Developer Portal."
```

Note that the above was with the current Preview version of VSfM.  I will now try reverting to the Stable version.

**Comment by baskren** [comment]
Just rolled back to **Stable** version of VSfM ... no luck.  Also, for grins, turned off **Project Options / Mac Build / Packaging / Create Installer Package** and tried again.  Still no luck.

![image](https://user-images.githubusercontent.com/2528888/87472181-86efb980-c5ed-11ea-863c-4a33525e27f3.png)

**Comment by baskren** [comment]
Lost over a week on this.

**Comment by CartBlanche** [comment]
@baskren Did you manage to get this working in the end?

**Comment by baskren** [comment]
I thought I did.  However, the app submission was stalled in Apple's review process for months.  Turns out their scripts couldn't support the character that I used in lieu of the space character.  They asked me to re-submit but, given the terrible effort to reward ratio I had on this project, I just gave up.  This was the last nail in the coffin form me for Xamarin.

**Comment by CartBlanche** [comment]
@baskren You wouldn't happen to remember what you had in your entitlements.plist to get this working?
